"""METHODS EXHIBIT — SIMULATED DATA. What within-window z-scoring of the
REGRESSOR does to a coefficient (PAPER_MASTER.md §5.2, §7.4).

NOTHING IN THIS FILE IS A RESULT. No outcome is estimated here. The effect is
PLANTED at a value chosen by us, the outcome is generated by this script, and
every row of every artifact it writes carries `data = SIMULATED`. The only real
data it touches are (a) the attention series itself, (b) the panel's (district,
day) skeleton and (c) the panel's noise structure — all of them inputs to a
simulation, never an estimate of anything.

WHAT §5.2 ACTUALLY CLAIMS, AND WHAT IT DOES NOT
-----------------------------------------------
    "The z-scoring artifact. The original specification standardised the
     awareness measure *within the analysis window*, so the variable's scale
     depended on what else was in the sample."

The object is the AWARENESS MEASURE — the right-hand side. CAI-D is the
regressor in the primary specification (03_main_model.py: `mh_narrow_share ~
cai_d lags 0..28 + leads 1..14 | CD + dow + month x year`). Standardising the
OUTCOME is a different operation with different consequences and is not what
went wrong here; an earlier draft of this exhibit demonstrated that instead and
was therefore aimed at the wrong object. This version is written against the
regressor.

The mechanism is one line of algebra and it is exact, not asymptotic. With
sample W, write the within-window standardised regressor as

    x_z = (x - m_W) / s_W,        m_W, s_W computed from the rows in W ONLY.

Then y = a + b*x + e is the same model as y = a' + (b*s_W)*x_z + e, so with the
same fixed effects, the same rows and the same outcome,

    b_z  ==  b_fixed * s_W        exactly, to floating point.

The coefficient an analyst reports is therefore the product of the effect and a
SAMPLE-DEFINITION CONSTANT. Change which rows are in W — a longer event window,
a dropped year, a robustness column that excludes one episode — and the number
moves with no change whatsoever in the data-generating process. That is the
defect: not bias, but an estimand that is a function of the sample.

Being precise about the charge, because the paper has to be: the z-arm
coefficient is NOT biased for its own estimand. "Effect per within-window SD of
attention" is a perfectly well-defined quantity and the arm estimates it
correctly. The failure is that this quantity is not the one the paper claims,
is not comparable across the rows of a robustness table, and is not comparable
to anyone else's estimate. A reader who sees a coefficient move 94% between two
columns reads instability in the effect; here the effect is identical by
construction and the movement is entirely s_W.

WHAT THIS EXHIBIT MEASURES (all figures below measured on the discovery sample,
2026-09-12, with the parameters this script prints on every run)
-------------------------------------------------------------------------------
Two channels are separated, because they are of very different size and the
earlier draft conflated them into a single window-length claim.

  1. WINDOW LENGTH — SMALL. Sweeping the half-window L over 7, 14, 28, 60 days
     around the 29 discovery episodes moves s_W only from 2.203 to 2.092, a
     5.3% spread, even though the REALISED sample length triples (15.00, 26.72,
     36.90, 45.10 district-days per episode-district; see below on why those
     are not 15, 29, 57, 121). Longer windows add quiet days, which pulls both
     the window mean and the window SD down, and those two effects largely
     cancel. A window-length claim here would be true but weak, and an exhibit
     built on it would be a weak exhibit.

  2. SAMPLE COMPOSITION — LARGE. Holding L at EVENT_WINDOW_POST = 14:
        all 29 discovery episodes          s_W = 2.146
        drop the single largest episode    s_W = 1.616   (0.75x)
        exclude 2020 (2017-2019)           s_W = 1.105   (0.51x)
        only 2020                          s_W = 3.515   (1.64x)
     The largest episode is 2020-05-26, peak CAI-D 12.45 (George Floyd; David
     McAtee). Leave-one-episode-out across all 29 spans s_W = 1.616 to 2.181, a
     factor of 1.35 from dropping ONE episode. Excluding 2020 — an entirely
     routine robustness column, and one this project would plausibly run for
     COVID reasons — nearly halves the reported coefficient while the planted
     effect is byte-identical.

  So: the scale depends on window length only weakly, and on WHICH EPISODES ARE
  IN THE SAMPLE very strongly. Both are "the analysis window" in §5.2's sense.
  The honest headline is the second one.

WHY THERE IS NO E[1/s] CONVEXITY TERM TO SEPARATE HERE
------------------------------------------------------
A previous version of this exhibit made a window-length claim that was
confounded with a pure Jensen artifact: it divided by a SAMPLE ESTIMATE of a
random SD, and E[1/s] > 1/E[s], so shrinking the window inflated the average
ratio even with no real change in scale — at realistic serial correlation that
convexity term was the larger half of the "window-length effect" being reported.

This exhibit does not have that term, by construction rather than by
correction. We CONDITION ON THE REALISED ATTENTION SERIES: x is the actual
CAI-D series as built, identical in every draw, and the only randomness is in
the simulated outcome. s_W is then a deterministic function of the sample
definition — a number you can compute before you fit anything — so there is no
expectation to take over it and no convexity. The identity check below verifies
this: b_z equals b_fixed * s_W in every single fit, not on average.

That is also the right stance for the paper's claim. An analyst holds one
attention series, not a distribution over them; the question "does my
coefficient move when I redefine the sample?" is a question about the series
they have.

DESIGN
------
Outcome (SIMULATED):

    y[i,t] = mu + cd[i] + dow[t] + day_shock[t] + BETA_TRUE * x[t] + e[i,t]

    e[i,t] = rho * e[i,t-1] + innovation        (AR(1) within district)

  x[t]        the real CAI-D series on the district-day's date, in the scale it
              is BUILT in — standardised once on the 2017-01-01..2019-12-31
              reference window by 12_build_cai.py, which is a FIXED scale that
              does not move when the analysis sample moves. That is what makes
              it the right comparison arm.
  mu, cd, dow, day_shock, rho, sigma
              MEASURED from the real panel, peeled off in the order they are
              added back so the components sum to the panel's variance rather
              than stacking on it (the same error 18_null_calibration.py made
              and fixed as finding S8). Measured 2026-09-12 on the discovery
              sample: mu = 0.085590, total SD = 0.042779, sigma = 0.038959,
              rho = 0.048170, component scales x sigma of district 0.335,
              day-of-week 0.130, citywide day shock 0.284.

              These are MEASURED, not copied. 18_null_calibration.py's source
              contains the literals 0.03 and 0.10 for sigma and mu; those are
              its no-panel FALLBACKS and it overwrites both from the panel on
              every real run. Lifting them would have produced a chimera — a
              DGP whose parameters belong to no dataset — so this script
              re-measures from the panel through the same guard and prints what
              it got. If the panel is absent the run stops rather than falling
              back to numbers it cannot justify.
  BETA_TRUE   a CHOSEN SIMULATION PARAMETER, not an estimate, and owned as
              such: 0.0010 share points per unit of CAI-D, about 1.2% of the
              panel's 0.0856 mean EDP share per unit. It is not this project's
              hypothesis, it is not derived from any outcome, and no reader
              should take it as an effect size. It exists only so that there is
              a known number for the two arms to distort or not distort.

Estimator: `y ~ x | ep_cd + dow`, SEs clustered on `incident_date`, on samples
built by `event_study.build_stack` — the same stacking, the same nearest-episode
assignment and the same clustering as the real design (S6: treatment is citywide
and assigned at the date level). The regressor is CONTINUOUS rather than a set
of event-time dummies because the defect is about a measure that has a scale,
and event-time dummies do not have one. This is the `fit_dose_response` shape,
not the `fit_event_study` shape.

Three arms:
  fixed_scale         x as built. The comparison arm. Recovers BETA_TRUE.
  within_window_z     (x - m_W)/s_W with m_W, s_W from the rows in W only.
                      This is the defect.
  within_window_centred
                      x - m_W. Fitted so that the decomposition is verified
                      rather than asserted, and it comes out EXACTLY EQUAL to
                      fixed_scale: the window mean is absorbed by the fixed
                      effects, so centring is harmless and only the DIVISION
                      does damage. That equality is an algebraic identity in
                      the fixed effects, it does not depend on the draw, and it
                      is therefore fitted ONCE per sample definition rather than
                      once per simulation — refitting it 25 times would measure
                      nothing new.

                      An earlier draft shipped a four-arm decomposition in which
                      two arms were bit-identical under the primary fixed
                      effects and the figure drew coincident curves nobody had
                      checked. Here the identity is the POINT, it is stated in
                      advance, and `check_centre_arm_identical` fails if it ever
                      stops holding — while `check_arms_distinct` fails if the
                      two arms that must differ ever coincide. Both directions
                      are checked because both are ways for an exhibit to be
                      silently empty.

WHY THE X-AXIS IS REALISED DAYS AND NOT L
-----------------------------------------
`build_stack` assigns a district-day claimed by two episode windows to the
NEARER episode (S5/E4), so a nominal ±L window is not ±L days of data once
episodes are closer together than 2L. Measured here: nominal 15, 29, 57, 121
district-days per episode-district come out as 15.00, 26.72, 36.90, 45.10. At
L = 60 the realised sample is 37% of its nominal length, and the episodes lost
are exactly the closely spaced ones. Plotting against L would put a label on the
axis that is not the quantity that varied, so the sweep is reported and plotted
against the realised count, with L kept as an annotation.

WHY THERE IS NO MINIMUM-WINDOW GUARD
------------------------------------
An earlier draft guarded with `if any(w < max(FIRST_WEEK_DAYS) + 1)`, i.e.
w < 8, against a default sweep whose shortest window was 7 — so the script
aborted with BLOCKED and exit 2 on its own defaults, including both of the usage
examples in its own docstring. It was also wrong on its own terms: `build_stack`
uses an INCLUSIVE `between(lo, hi)`, so L = 7 spans rel_day -7..+7 and all eight
of days 0..7 are identified. Re-measured 2026-09-12 on the discovery stack at
L = 7: rel_day runs -7..+7, all of 0..7 come back from `_rel_day_coefs`, and
`first_week_effect` reports ndays = 8 with none dropped. The correct predicate
would have been `w < max(FIRST_WEEK_DAYS)`.

This exhibit needs no such guard at all, because it never forms a first-week
contrast: the statistic is a single coefficient on a continuous regressor, which
is identified at every L in the sweep. A guard that cannot bind is a guard that
can only misfire, so there isn't one. The defaults run.

SELF-CHECKS
-----------
Seven checks run on every invocation, and each one is then run again against a
DELIBERATELY BROKEN copy of the same output and required to FAIL. A check that
passes on the mutant is itself a failure and stops the run. This is here because
of a specific prior defect: a check called `outputs_labelled_simulated` built a
frame with 'data' as a ROW LABEL in a `parameter` column and then tested
`if 'data' not in t.columns` — a condition that was true of every possible
output, so the check reported problems always and exited 1 always. It could not
pass. The inverse failure — a check that cannot fail — is §7.5's subject and the
most transferable lesson in the project. Running both directions on every
invocation is the only way to know which kind you have written.

Compute: deliberately small and single-process. Two fits per (sample definition
x draw) plus one per sample definition — 459 fits at the defaults — and the full
29-episode leave-one-out costs no fits at all. Measured 2026-09-12: the default
run (four windows, five composition samples, 25 draws) takes about 80 seconds of
one core. There is no ProcessPoolExecutor and no randomization inference here:
18_null_calibration.py needs workers because its estimator is inside a 200 x 200
loop, and this one is not.

Outputs (every row of every file carries `data = SIMULATED`):
    outputs/tables/zscore_simulation.csv          one row per sample x arm
    outputs/tables/zscore_simulation_params.csv   DGP parameters and provenance
    outputs/figures/zscore_simulation.png/.pdf    drawn by READING BACK the CSV
                                                  above, so the figure cannot
                                                  disagree with the table
                                                  (REWORK_PLAN §7)

Usage:
    python 25_zscore_simulation.py
    python 25_zscore_simulation.py --sims 100
    python 25_zscore_simulation.py --sims 3 --windows 7 14 --no-figure
"""

import argparse

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pyfixest as pf

from config import (
    DATA_PROCESSED,
    DATA_REFERENCE,
    EPISODE_LIST_PRIMARY,
    EVENT_WINDOW_POST,
    EVENT_WINDOW_POST_SENSITIVITY,
    MIN_TOTAL_CALLS_FOR_SHARE,
    OUTPUTS_FIGURES,
    OUTPUTS_TABLES,
    PRIMARY_AWARENESS,
)
from event_study import CLUSTER_VAR, build_stack
from freeze_guard import active_windows, freeze_banner, select_sample

# The label that marks every artifact. One constant, used for the column NAME's
# contents and for the check, so the check and the writer cannot disagree about
# what "labelled" means.
SIM_LABEL = "SIMULATED"
LABEL_COL = "data"

# CHOSEN simulation parameter. See the docstring: this is not an effect size,
# not a hypothesis, and not derived from any outcome. Share points per unit of
# CAI-D in its built (2017-2019 reference) scale.
BETA_TRUE = 0.0010

# Tolerances. The identity b_z = b_fixed * s_W is exact in exact arithmetic; the
# slack is for pyfixest's alternating-projections demeaning, which is iterative.
IDENTITY_RTOL = 1e-6
CENTRE_RTOL = 1e-6
# Two arms are "distinct" only if they differ by more than this in relative
# terms. A tiny numerical difference is not distinctness.
DISTINCT_RTOL = 0.01

BLUE, VIOLET, GRAY, RED = "#2a78d6", "#4a3aa7", "#52514e", "#e34948"

parser = argparse.ArgumentParser()
parser.add_argument("--sims", type=int, default=25,
                    help="simulated outcome draws per sample definition")
parser.add_argument("--windows", type=int, nargs="+", default=None,
                    help="half-window lengths for the length sweep; default is "
                         "EVENT_WINDOW_POST//2 plus EVENT_WINDOW_POST plus "
                         "EVENT_WINDOW_POST_SENSITIVITY")
parser.add_argument("--beta", type=float, default=BETA_TRUE,
                    help="planted effect, share points per unit of the awareness index")
parser.add_argument("--seed", type=int, default=25_20260912)
parser.add_argument("--no-figure", action="store_true")
args = parser.parse_args()

BETA = args.beta
WINDOWS = sorted(set(args.windows if args.windows is not None
                     else [EVENT_WINDOW_POST // 2, EVENT_WINDOW_POST,
                           *EVENT_WINDOW_POST_SENSITIVITY]))
PRIMARY_L = EVENT_WINDOW_POST if EVENT_WINDOW_POST in WINDOWS else WINDOWS[len(WINDOWS) // 2]

OUTPUTS_TABLES.mkdir(parents=True, exist_ok=True)
OUTPUTS_FIGURES.mkdir(parents=True, exist_ok=True)
rng = np.random.default_rng(args.seed)

print("=" * 78)
print("25_zscore_simulation — SIMULATED DATA, METHODS EXHIBIT, NOT A RESULT")
print("The outcome is generated by this script. No effect is estimated here.")
print("=" * 78)
freeze_banner("25_zscore_simulation")


# ---------------------------------------------------------------------------
# Inputs. Every read of a project artifact goes through select_sample, which
# both filters to the permitted sample and proves nothing else got through
# (finding D3 — a filter and a guard that are separate operations make the guard
# tautological). The panel is read for its SKELETON and its NOISE STRUCTURE
# only; no outcome is estimated anywhere in this file.
# ---------------------------------------------------------------------------
panel_path = DATA_PROCESSED / "panel_cd_day.parquet"
if not panel_path.exists():
    raise SystemExit(
        f"{panel_path} is missing. This exhibit takes mu, sigma, rho and the "
        "component scales FROM THE PANEL; there is no fallback, because a DGP "
        "with invented parameters is a chimera and the numbers it produces "
        "belong to no dataset. Build the panel first (01_build_panel.py).")

panel = pd.read_parquet(panel_path)
panel["incident_date"] = pd.to_datetime(panel["incident_date"])
panel = select_sample(panel, where="25_zscore_simulation:panel")
panel = panel[panel["total_calls"] >= MIN_TOTAL_CALLS_FOR_SHARE].copy()

cai = pd.read_parquet(DATA_PROCESSED / "cai_daily.parquet")
cai["date"] = pd.to_datetime(cai["date"])
cai = select_sample(cai, date_col="date", where="25_zscore_simulation:cai")
if PRIMARY_AWARENESS not in cai.columns:
    raise SystemExit(f"cai_daily.parquet has no {PRIMARY_AWARENESS} column")

panel = panel.merge(cai[["date", PRIMARY_AWARENESS]].rename(columns={PRIMARY_AWARENESS: "x"}),
                    left_on="incident_date", right_on="date", how="left")
if panel["x"].isna().any():
    raise SystemExit(f"{int(panel['x'].isna().sum()):,} district-days have no "
                     f"{PRIMARY_AWARENESS}; the regressor must be complete on the "
                     "skeleton or the sample definition, not the measure, would "
                     "be doing the work.")

# Episodes by CONSTANT, never by filename (the frozen list and the rebuilt list
# are not interchangeable; see config.EPISODE_LIST_PRIMARY). Which episodes are
# eligible is DERIVED from the freeze rather than from the list's own `period`
# column, so the two can never disagree about what this run may touch.
episodes = pd.read_csv(DATA_REFERENCE / EPISODE_LIST_PRIMARY, parse_dates=["start"])
_win = active_windows()
_eligible = pd.Series(False, index=episodes.index)
for lo, hi in _win:
    _eligible |= episodes["start"].between(lo, hi)
episodes = episodes[_eligible].sort_values("start").reset_index(drop=True)
if len(episodes) < 3:
    raise SystemExit(f"only {len(episodes)} episodes fall inside {_win}; the "
                     "composition sweep needs a list to vary.")
ALL_STARTS = episodes["start"].tolist()
print(f"episodes inside the permitted sample: {len(ALL_STARTS)} "
      f"({ALL_STARTS[0].date()}..{ALL_STARTS[-1].date()}) from {EPISODE_LIST_PRIMARY}")

# ---------------------------------------------------------------------------
# Noise structure, MEASURED from the panel (never lifted from another script's
# source). Each component is estimated and REMOVED before the next is estimated,
# so the pieces sum to the panel's variance instead of stacking on it — the
# error 18_null_calibration.py made and fixed as finding S8.
# ---------------------------------------------------------------------------
s = panel.dropna(subset=["edp_share"]).sort_values(["communitydistrict", "incident_date"])
MU = float(s["edp_share"].mean())
TOTAL_SD = float(s["edp_share"].std())

r = s["edp_share"] - s.groupby("communitydistrict")["edp_share"].transform("mean")
CD_SD = float(s.groupby("communitydistrict")["edp_share"].mean().std())
_dowm = r.groupby(s["incident_date"].dt.dayofweek).transform("mean")
r = r - _dowm
DOW_SD = float(_dowm.groupby(s["incident_date"].dt.dayofweek).first().std())
_daym = r.groupby(s["incident_date"]).transform("mean")
r = r - _daym
DAY_SD = float(_daym.groupby(s["incident_date"]).first().std())
SIGMA = float(r.std())
_lag = r.groupby(s["communitydistrict"]).shift(1)
_ok = _lag.notna() & r.notna()
RHO = float(np.corrcoef(r[_ok], _lag[_ok])[0, 1])

print(f"measured from the panel: mu={MU:.6f} total_sd={TOTAL_SD:.6f} "
      f"sigma={SIGMA:.6f} rho={RHO:.6f}")
print(f"  component SDs (x sigma): district={CD_SD / SIGMA:.3f} "
      f"dow={DOW_SD / SIGMA:.3f} day_shock={DAY_SD / SIGMA:.3f}")
print(f"  implied total sd "
      f"{np.sqrt(SIGMA ** 2 + CD_SD ** 2 + DOW_SD ** 2 + DAY_SD ** 2):.6f} "
      f"against the panel's {TOTAL_SD:.6f}")
print(f"CHOSEN (not measured): BETA_TRUE={BETA} share points per unit of "
      f"{PRIMARY_AWARENESS}, ~{100 * BETA / MU:.2f}% of the mean share per unit")

# ---------------------------------------------------------------------------
# The skeleton, as arrays. The outcome is drawn on the full (district x day)
# grid once per simulation and then read onto each sample's rows by index, so
# every sample definition sees the SAME draw. That makes the sweep paired: any
# difference between two sample definitions is the sample definition, not the
# luck of the draw.
# ---------------------------------------------------------------------------
CDS = np.array(sorted(panel["communitydistrict"].unique()))
DATES = np.array(sorted(panel["incident_date"].unique()))
CD_POS = {c: i for i, c in enumerate(CDS)}
DATE_POS = {d: t for t, d in enumerate(DATES)}
N, T = len(CDS), len(DATES)
DOW_OF_DATE = pd.to_datetime(pd.Series(DATES)).dt.dayofweek.to_numpy()
X_OF_DATE = (panel.drop_duplicates("incident_date")
                  .set_index("incident_date")["x"]
                  .reindex(pd.to_datetime(DATES)).to_numpy())
print(f"skeleton: {N} districts x {T} days = {N * T:,} cells, "
      f"{len(panel):,} panel rows after total_calls >= {MIN_TOTAL_CALLS_FOR_SHARE}")

# The city's fixed features are drawn ONCE, not per simulation: a district's
# level and a day-of-week's level are properties of the city, not noise the
# analyst re-rolls. Only the AR(1) series and the citywide day shock are redrawn.
CD_EFFECT = rng.normal(0, CD_SD, N)
DOW_EFFECT = rng.normal(0, DOW_SD, 7)


def simulate_outcome(r_):
    """One draw of the SIMULATED outcome on the whole skeleton. Returns (N, T)."""
    innov = r_.normal(0, SIGMA * np.sqrt(max(1 - RHO ** 2, 0.0)), (N, T))
    e = np.empty((N, T))
    e[:, 0] = r_.normal(0, SIGMA, N)
    for t in range(1, T):
        e[:, t] = RHO * e[:, t - 1] + innov[:, t]
    day_shock = r_.normal(0, DAY_SD, T)
    return (MU + CD_EFFECT[:, None] + DOW_EFFECT[DOW_OF_DATE][None, :]
            + day_shock[None, :] + BETA * X_OF_DATE[None, :] + e)


# ---------------------------------------------------------------------------
# Sample definitions. Two blocks, because the two channels are of very different
# size and an exhibit that reports only their sum tells the reader nothing about
# which one to worry about.
#
#   window_length  the same episodes, longer and longer windows.
#   composition    the same window, different episodes — each of these is a
#                  choice a working analyst actually makes, not an arbitrary
#                  subset: a leave-one-out, a "drop the COVID year" robustness
#                  column, and the complements of both.
# ---------------------------------------------------------------------------
_largest_i = int(episodes["peak_cai_d"].idxmax()) if "peak_cai_d" in episodes.columns else 0
_largest_start = ALL_STARTS[_largest_i]
_years = sorted({d.year for d in ALL_STARTS})
_last_year = _years[-1]

SAMPLES = []
for L in WINDOWS:
    SAMPLES.append(dict(block="window_length", sample_id=f"L{L}_all_episodes",
                        label=f"all episodes, +/-{L}d", L=L, starts=ALL_STARTS))

_comp = [
    (f"primary_L{PRIMARY_L}", "all episodes (primary)", ALL_STARTS),
    ("drop_largest_episode",
     f"drop the largest episode ({_largest_start.date()})",
     [d for d in ALL_STARTS if d != _largest_start]),
    (f"exclude_{_last_year}", f"exclude {_last_year}",
     [d for d in ALL_STARTS if d.year != _last_year]),
    (f"only_{_last_year}", f"only {_last_year}",
     [d for d in ALL_STARTS if d.year == _last_year]),
    (f"first_half_{_years[0]}_{_years[len(_years) // 2 - 1]}",
     f"first half ({_years[0]}-{_years[len(_years) // 2 - 1]})",
     [d for d in ALL_STARTS if d.year <= _years[len(_years) // 2 - 1]]),
]
for sid, lab, sts in _comp:
    if len(sts) >= 2:
        SAMPLES.append(dict(block="composition", sample_id=sid, label=lab,
                            L=PRIMARY_L, starts=sts))


def prepare(sample):
    """Build a sample's stack once: rows, index maps, and the window constants.

    m_W and s_W are computed HERE, from the estimation rows and nothing else —
    which is precisely the operation under critique. They are deterministic
    given the sample definition: no outcome, no draw and no estimation enters
    them, which is why there is no expectation to take over s_W and no
    convexity term in anything below.
    """
    st = build_stack(panel, sample["starts"], sample["L"], sample["L"])
    if st.empty:
        return None
    st = st.dropna(subset=["x"]).copy()
    if st.empty or st["episode"].nunique() < 2:
        return None

    # ddof=0 to match event_study.fit_dose_response, which standardises episode
    # intensity within the stack the same way. That function does this on
    # purpose and discloses it; the coefficient it reports is explicitly "per SD
    # of episode size IN THIS STACK". This exhibit is the cost of that choice
    # when the coefficient is instead read as a fixed-scale quantity.
    m_w = float(st["x"].mean())
    s_w = float(st["x"].std(ddof=0))
    if not np.isfinite(s_w) or s_w <= 0:
        return None

    st["x_fixed"] = st["x"]
    st["x_z"] = (st["x"] - m_w) / s_w
    st["x_centred"] = st["x"] - m_w

    ep_cd_groups = st.groupby(["episode", "communitydistrict"]).ngroups
    return dict(
        **sample,
        stack=st,
        cd_idx=np.array([CD_POS[c] for c in st["communitydistrict"]]),
        t_idx=np.array([DATE_POS[d] for d in st["incident_date"]]),
        m_w=m_w, s_w=s_w,
        n_rows=len(st),
        n_episodes=int(st["episode"].nunique()),
        n_dates=int(st["incident_date"].nunique()),
        realised_days=len(st) / ep_cd_groups,
        nominal_days=2 * sample["L"] + 1,
        date_min=pd.Timestamp(st["incident_date"].min()),
        date_max=pd.Timestamp(st["incident_date"].max()),
    )


PREPARED = []
for sample in SAMPLES:
    p = prepare(sample)
    if p is None:
        print(f"  {sample['sample_id']}: not estimable, skipped")
        continue
    PREPARED.append(p)
    print(f"  {p['sample_id']:<28} eps={p['n_episodes']:>3} rows={p['n_rows']:>6,} "
          f"nominal_days={p['nominal_days']:>4} realised={p['realised_days']:>6.2f} "
          f"m_W={p['m_w']:>7.4f} s_W={p['s_w']:.4f}")
if not PREPARED:
    raise SystemExit("no sample definition produced an estimable stack")

ARMS = {"fixed_scale": "x_fixed", "within_window_z": "x_z",
        "within_window_centred": "x_centred"}


def fit(st, xcol):
    """`y_sim ~ x | ep_cd + dow`, clustered on the date. Returns (coef, se)."""
    m = pf.feols(f"y_sim ~ {xcol} | ep_cd + dow", st, vcov={"CRV1": CLUSTER_VAR})
    return float(m.coef().loc[xcol]), float(m.se().loc[xcol])


# ---------------------------------------------------------------------------
# The simulation itself.
# ---------------------------------------------------------------------------
EXHIBIT_MIN_SIMS = 25
if args.sims < EXHIBIT_MIN_SIMS:
    # A warning, NOT a gate, and the distinction is load-bearing. Everything the
    # exhibit actually claims — s_W, the identity, the ratio of the z arm to the
    # fixed arm — is deterministic given the sample definition and does not
    # depend on the number of draws at all. What the draws buy is precision on
    # `coef_mean`, i.e. the demonstration that the distortion is large beside
    # sampling error. So a 3-draw run is a legitimate diagnostic whose headline
    # numbers are exact; it is only the standard errors that are thin.
    print(f"\nNOTE: {args.sims} draws (< {EXHIBIT_MIN_SIMS}). The distortion figures "
          "are exact regardless — they are deterministic in the sample definition "
          "— but coef_mean is noisy. Use >= 25 draws for the published exhibit.")

print(f"\nrunning {args.sims} simulated draws x {len(PREPARED)} sample definitions")
draws = {p["sample_id"]: {a: [] for a in ARMS} for p in PREPARED}
for k in range(args.sims):
    Y = simulate_outcome(rng)
    for p in PREPARED:
        st = p["stack"]
        st["y_sim"] = Y[p["cd_idx"], p["t_idx"]]
        for arm, xcol in ARMS.items():
            # The centred arm equals the fixed arm as an algebraic identity in
            # the fixed effects, for ANY outcome. It is fitted once so that the
            # identity is verified rather than asserted; fitting it every draw
            # would add cost and measure nothing.
            if arm == "within_window_centred" and k > 0:
                continue
            draws[p["sample_id"]][arm].append(fit(st, xcol))
    if args.sims >= 10 and (k + 1) % max(1, args.sims // 4) == 0:
        print(f"  draw {k + 1}/{args.sims}", flush=True)

rows = []
for p in PREPARED:
    for arm in ARMS:
        d = np.array(draws[p["sample_id"]][arm], dtype=float)
        if d.size == 0:
            continue
        coefs, ses = d[:, 0], d[:, 1]
        # What the identity says this arm's coefficient must be: b_fixed * s_W
        # for the z arm, b_fixed for the others. Written down as a PREDICTION so
        # the check compares against it rather than re-deriving it from the same
        # numbers it is checking.
        #
        # The comparison is against the fixed arm ON THE SAME DRAWS. The centred
        # arm is fitted once and the others every draw, so comparing it against
        # the fixed arm's mean over ALL draws compares two different things and
        # fails by the size of the Monte Carlo noise. That is not hypothetical:
        # the first version of this file did exactly that, and the check below
        # failed on correct output with a 0.33 relative difference. Draws are
        # appended in order, so the first n_fits fixed-arm draws are the matching
        # ones.
        fixed_all = np.array(draws[p["sample_id"]]["fixed_scale"], dtype=float)[:, 0]
        fixed_matched = float(np.mean(fixed_all[:d.shape[0]]))
        predicted = fixed_matched * (p["s_w"] if arm == "within_window_z" else 1.0)
        rows.append({
            LABEL_COL: SIM_LABEL,
            "block": p["block"],
            "sample_id": p["sample_id"],
            "sample_label": p["label"],
            "nominal_half_window_days": p["L"],
            "nominal_days_per_episode_district": p["nominal_days"],
            "realised_days_per_episode_district": round(p["realised_days"], 4),
            "n_episodes": p["n_episodes"],
            "n_rows": p["n_rows"],
            "n_dates": p["n_dates"],
            "sample_date_min": str(p["date_min"].date()),
            "sample_date_max": str(p["date_max"].date()),
            "window_mean_x": round(p["m_w"], 6),
            "window_sd_x": round(p["s_w"], 6),
            "arm": arm,
            "n_fits": int(d.shape[0]),
            "beta_true": BETA,
            "coef_mean": float(np.mean(coefs)),
            "coef_sd_across_draws": float(np.std(coefs, ddof=1)) if d.shape[0] > 1 else np.nan,
            "se_mean": float(np.mean(ses)),
            "coef_over_beta_true": float(np.mean(coefs) / BETA),
            "identity_predicted_coef": predicted,
            "identity_abs_err": abs(float(np.mean(coefs)) - predicted),
        })

# ---------------------------------------------------------------------------
# Leave-one-episode-out, ANALYTIC. s_W needs no outcome and no fit, and the
# identity above — verified on every fitted row — says the z-arm coefficient is
# beta * s_W. So the full leave-one-out is reported without 29 more regressions,
# and is marked n_fits = 0 and arm `within_window_z_analytic` so nobody mistakes
# it for a fitted row. If the identity check ever fails, these rows are void,
# which is the correct coupling.
# ---------------------------------------------------------------------------
loo_rows = []
if len(ALL_STARTS) >= 3:
    for i, dropped in enumerate(ALL_STARTS):
        sub = [d for j, d in enumerate(ALL_STARTS) if j != i]
        p = prepare(dict(block="leave_one_episode_out",
                         sample_id=f"drop_{dropped.date()}",
                         label=f"drop episode starting {dropped.date()}",
                         L=PRIMARY_L, starts=sub))
        if p is None:
            continue
        loo_rows.append({
            LABEL_COL: SIM_LABEL,
            "block": "leave_one_episode_out",
            "sample_id": p["sample_id"],
            "sample_label": p["label"],
            "nominal_half_window_days": p["L"],
            "nominal_days_per_episode_district": p["nominal_days"],
            "realised_days_per_episode_district": round(p["realised_days"], 4),
            "n_episodes": p["n_episodes"],
            "n_rows": p["n_rows"],
            "n_dates": p["n_dates"],
            "sample_date_min": str(p["date_min"].date()),
            "sample_date_max": str(p["date_max"].date()),
            "window_mean_x": round(p["m_w"], 6),
            "window_sd_x": round(p["s_w"], 6),
            "arm": "within_window_z_analytic",
            "n_fits": 0,
            "beta_true": BETA,
            "coef_mean": BETA * p["s_w"],
            "coef_sd_across_draws": np.nan,
            "se_mean": np.nan,
            "coef_over_beta_true": p["s_w"],
            "identity_predicted_coef": BETA * p["s_w"],
            "identity_abs_err": 0.0,
        })

out = pd.DataFrame(rows + loo_rows)

params = pd.DataFrame([
    # Deliberately NOT a row whose `parameter` is "data". A previous version of
    # this exhibit put the SIMULATED label in a row of a `parameter` column and
    # then wrote a check asking whether "data" was a COLUMN — two different
    # things wearing one name, and the check could never pass. The label lives
    # in a real column (inserted below, on every row of both files) and nothing
    # in the `parameter` column shares its name.
    ("artifact_kind", "simulation output", "this file describes a simulation"),
    ("script", "25_zscore_simulation.py", "provenance"),
    ("beta_true", BETA, "CHOSEN simulation parameter, not an estimate"),
    ("awareness_measure", PRIMARY_AWARENESS, "config.PRIMARY_AWARENESS"),
    ("episode_list", EPISODE_LIST_PRIMARY, "config.EPISODE_LIST_PRIMARY"),
    ("n_episodes_available", len(ALL_STARTS), "inside freeze_guard.active_windows()"),
    ("freeze_windows", ";".join(f"{a.date()}..{b.date()}" for a, b in _win),
     "freeze_guard.active_windows()"),
    ("n_sims", args.sims, "command line"),
    ("seed", args.seed, "command line"),
    ("mu_edp_share", MU, "MEASURED from panel_cd_day.parquet via select_sample"),
    ("total_sd_edp_share", TOTAL_SD, "MEASURED from the panel"),
    ("sigma_ar1", SIGMA, "MEASURED from the panel, after peeling cd/dow/day"),
    ("rho_ar1", RHO, "MEASURED from the panel residual, not the level"),
    ("district_sd", CD_SD, "MEASURED from the panel"),
    ("dow_sd", DOW_SD, "MEASURED from the panel"),
    ("day_shock_sd", DAY_SD, "MEASURED from the panel"),
    ("min_total_calls", MIN_TOTAL_CALLS_FOR_SHARE, "config.MIN_TOTAL_CALLS_FOR_SHARE"),
    ("cluster_var", CLUSTER_VAR, "event_study.CLUSTER_VAR"),
    ("fixed_effects", "ep_cd + dow", "matches the stacked design"),
    ("standardisation_ddof", 0, "matches event_study.fit_dose_response"),
], columns=["parameter", "value", "source"])
params.insert(0, LABEL_COL, SIM_LABEL)

MAIN_CSV = OUTPUTS_TABLES / "zscore_simulation.csv"
PARAMS_CSV = OUTPUTS_TABLES / "zscore_simulation_params.csv"
out.to_csv(MAIN_CSV, index=False)
params.to_csv(PARAMS_CSV, index=False)
print(f"\nwrote {MAIN_CSV} ({len(out)} rows) and {PARAMS_CSV} ({len(params)} rows)")


# ---------------------------------------------------------------------------
# SELF-CHECKS. Each is a pure function of the two output frames, returning
# (ok, detail). Each is then re-run against a mutated copy and REQUIRED TO FAIL.
#
# The prior defect this apparatus exists for: a check named
# `outputs_labelled_simulated` wrote 'data' as a ROW LABEL in a `parameter`
# column and then asked `if 'data' not in t.columns`. That condition was true of
# every possible output, so the check reported problems on correct output and
# exited 1 unconditionally. It had never passed and could not. Its mirror image
# — a check that cannot fail — is §7.5's subject. Running both directions on
# every invocation is the only way to know which kind you have.
# ---------------------------------------------------------------------------
def check_label_present(main, par):
    """Every row of every artifact carries data = SIMULATED, as a COLUMN."""
    for name, t in (("main", main), ("params", par)):
        if LABEL_COL not in t.columns:
            return False, f"{name} has no '{LABEL_COL}' column"
        if len(t) == 0:
            return False, f"{name} is empty"
        bad = (t[LABEL_COL] != SIM_LABEL).sum()
        if bad:
            return False, f"{name} has {bad} row(s) not labelled {SIM_LABEL}"
    return True, f"{len(main)} + {len(par)} rows labelled {SIM_LABEL}"


def check_arms_distinct(main, par):
    """fixed_scale and within_window_z must not coincide anywhere."""
    f = main[main["arm"] == "fixed_scale"].set_index("sample_id")["coef_mean"]
    z = main[main["arm"] == "within_window_z"].set_index("sample_id")["coef_mean"]
    common = f.index.intersection(z.index)
    if len(common) == 0:
        return False, "no sample has both arms"
    rel = (z[common] - f[common]).abs() / f[common].abs().clip(lower=1e-30)
    bad = rel[rel <= DISTINCT_RTOL]
    if len(bad):
        return False, (f"{len(bad)} sample(s) where the two arms coincide within "
                       f"{DISTINCT_RTOL:.0%}: {list(bad.index)[:3]}")
    return True, f"{len(common)} samples, min relative gap {rel.min():.3f}"


def check_centre_arm_identical(main, par):
    """Centring is absorbed by the fixed effects: the centred arm MUST equal
    the fixed arm. This is the claim; if it stops holding, the decomposition
    into "centring is harmless, dividing is not" is wrong."""
    c = main[main["arm"] == "within_window_centred"]
    if len(c) == 0:
        return False, "the centred arm was never fitted"
    rel = ((c["coef_mean"] - c["identity_predicted_coef"]).abs()
           / c["identity_predicted_coef"].abs().clip(lower=1e-30))
    bad = rel[rel > CENTRE_RTOL]
    if len(bad):
        return False, (f"{len(bad)} sample(s) where centring changed the coefficient: "
                       f"max relative difference {rel.max():.3e}")
    return True, f"{len(c)} samples, max relative difference {rel.max():.3e}"


def check_identity_holds(main, par):
    """b_z == b_fixed * s_W, exactly, on every fitted row."""
    z = main[(main["arm"] == "within_window_z") & (main["n_fits"] > 0)]
    if len(z) == 0:
        return False, "no fitted within_window_z rows"
    rel = (z["identity_abs_err"] / z["identity_predicted_coef"].abs().clip(lower=1e-30))
    bad = rel[rel > IDENTITY_RTOL]
    if len(bad):
        return False, (f"{len(bad)} row(s) violate b_z = b_fixed * s_W; "
                       f"worst relative error {rel.max():.3e}")
    return True, f"{len(z)} rows, worst relative error {rel.max():.3e}"


def check_planted_effect_recovered(main, par):
    """The fixed-scale arm must return the planted effect. If it does not, the
    simulation is miswired and nothing else in the file means anything."""
    f = main[(main["arm"] == "fixed_scale") & (main["n_fits"] > 0)]
    if len(f) == 0:
        return False, "no fitted fixed_scale rows"
    worst, worst_id = 0.0, None
    for _, row in f.iterrows():
        n = max(int(row["n_fits"]), 1)
        mc = (row["coef_sd_across_draws"] / np.sqrt(n) if n >= 5
              and np.isfinite(row["coef_sd_across_draws"]) else row["se_mean"])
        if not np.isfinite(mc) or mc <= 0:
            return False, f"{row['sample_id']}: no usable band"
        t = abs(row["coef_mean"] - row["beta_true"]) / mc
        if t > worst:
            worst, worst_id = t, row["sample_id"]
    if worst > 4.0:
        return False, (f"{worst_id}: fixed-scale mean is {worst:.1f} standard errors "
                       f"from beta_true")
    return True, f"worst departure {worst:.2f} SE (at {worst_id})"


def check_realised_days_reported(main, par):
    """The sweep's x-axis must be the quantity that varied. Nearest-episode
    assignment truncates long windows, so realised length is BELOW nominal and
    the gap grows with L. A table that reports only nominal L labels its axis
    with a number that is not what changed."""
    w = (main[main["block"] == "window_length"]
         .drop_duplicates("sample_id")
         .sort_values("nominal_half_window_days"))
    if len(w) < 2:
        return False, "fewer than two window-length samples"
    if (w["realised_days_per_episode_district"]
            > w["nominal_days_per_episode_district"] + 1e-9).any():
        return False, "a realised length exceeds its nominal length"
    longest = w.iloc[-1]
    if (longest["realised_days_per_episode_district"]
            >= longest["nominal_days_per_episode_district"] - 1e-9):
        return False, (f"realised == nominal at the longest window "
                       f"(L={int(longest['nominal_half_window_days'])}); either "
                       "truncation stopped happening or the nominal label is being "
                       "reported as if it were realised")
    r = w["realised_days_per_episode_district"].to_numpy()
    if not np.all(np.diff(r) > 0):
        return False, f"realised length is not increasing in L: {list(r)}"
    return True, (f"realised {[round(float(v), 2) for v in r]} against nominal "
                  f"{[int(v) for v in w['nominal_days_per_episode_district']]}")


def check_dates_inside_freeze(main, par):
    """No sample may reach outside the permitted window. select_sample already
    filtered the inputs; this proves the SAMPLES BUILT FROM THEM stayed inside,
    which is a different statement and the one the artifact asserts."""
    wins = [(pd.Timestamp(a), pd.Timestamp(b)) for a, b in active_windows()]
    lo = pd.to_datetime(main["sample_date_min"])
    hi = pd.to_datetime(main["sample_date_max"])
    inside = pd.Series(False, index=main.index)
    for a, b in wins:
        inside |= lo.between(a, b) & hi.between(a, b)
    if not inside.all():
        bad = main.loc[~inside, "sample_id"].tolist()[:3]
        return False, f"{int((~inside).sum())} sample(s) outside {wins}: {bad}"
    return True, f"all {len(main)} rows inside {[(str(a.date()), str(b.date())) for a, b in wins]}"


# Each mutation must be one that a real defect would produce, and must be the
# defect the paired check is written against.
def _mut_label(main, par):
    m = main.copy()
    m.loc[m.index[0], LABEL_COL] = "REAL"
    return m, par


def _mut_arms_coincide(main, par):
    m = main.copy()
    f = m[m["arm"] == "fixed_scale"].set_index("sample_id")["coef_mean"]
    sel = m["arm"] == "within_window_z"
    m.loc[sel, "coef_mean"] = m.loc[sel, "sample_id"].map(f).to_numpy()
    return m, par


def _mut_centre_differs(main, par):
    m = main.copy()
    sel = m["arm"] == "within_window_centred"
    m.loc[sel, "coef_mean"] = m.loc[sel, "coef_mean"] * 1.05
    return m, par


def _mut_identity_broken(main, par):
    m = main.copy()
    sel = (m["arm"] == "within_window_z") & (m["n_fits"] > 0)
    m.loc[sel, "identity_predicted_coef"] = m.loc[sel, "identity_predicted_coef"] * 1.05
    m.loc[sel, "identity_abs_err"] = (m.loc[sel, "coef_mean"]
                                      - m.loc[sel, "identity_predicted_coef"]).abs()
    return m, par


def _mut_effect_lost(main, par):
    m = main.copy()
    sel = m["arm"] == "fixed_scale"
    m.loc[sel, "coef_mean"] = m.loc[sel, "coef_mean"] * 3.0
    return m, par


def _mut_nominal_as_realised(main, par):
    m = main.copy()
    m["realised_days_per_episode_district"] = m["nominal_days_per_episode_district"]
    return m, par


def _mut_date_outside(main, par):
    m = main.copy()
    m.loc[m.index[0], "sample_date_max"] = "2099-12-31"
    return m, par


CHECKS = [
    ("label_present", check_label_present, _mut_label),
    ("arms_distinct", check_arms_distinct, _mut_arms_coincide),
    ("centre_arm_identical", check_centre_arm_identical, _mut_centre_differs),
    ("identity_holds", check_identity_holds, _mut_identity_broken),
    ("planted_effect_recovered", check_planted_effect_recovered, _mut_effect_lost),
    ("realised_days_reported", check_realised_days_reported, _mut_nominal_as_realised),
    ("dates_inside_freeze", check_dates_inside_freeze, _mut_date_outside),
]

print("\n" + "-" * 78)
print("SELF-CHECKS — each run on the real output (must PASS) and on a broken")
print("copy (must FAIL). A check that survives its own mutation is a defect.")
print("-" * 78)
failures = []
for name, fn, mut in CHECKS:
    ok, detail = fn(out, params)
    m_main, m_par = mut(out, params)
    mut_ok, mut_detail = fn(m_main, m_par)
    verdict = "PASS" if ok else "FAIL"
    print(f"  {name:<26} {verdict}")
    print(f"      real output: {detail}")
    # The mutant's REASON is printed, not just the fact that it failed. A check
    # can fail a mutant for an unrelated reason and look healthy while being
    # blind to the defect it was written for; printing the reason is what lets a
    # reviewer see that the mutation and the complaint match.
    print(f"      mutated copy: {'FAILS as required' if not mut_ok else 'STILL PASSES'}"
          f" -- {mut_detail}")
    if not ok:
        failures.append(f"{name}: {detail}")
    if mut_ok:
        failures.append(f"{name}: the mutated output also passed ({mut_detail}); "
                        "this check cannot detect the defect it is written for")

# ---------------------------------------------------------------------------
# Figure, drawn by READING BACK the CSV just written, so it cannot disagree with
# the table (REWORK_PLAN §7 — 08_figures.py reads only saved tables for exactly
# this reason, and an exhibit that estimates and plots in one process is the
# usual way a figure and a table drift apart).
# ---------------------------------------------------------------------------
if not args.no_figure and not failures:
    plot = pd.read_csv(MAIN_CSV)
    plt.rcParams.update({
        "figure.dpi": 120, "savefig.dpi": 300, "font.size": 9,
        "axes.spines.top": False, "axes.spines.right": False,
        "axes.grid": True, "grid.alpha": 0.25, "grid.linewidth": 0.5,
        "axes.axisbelow": True, "font.family": "DejaVu Sans",
    })
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(11.5, 4.2),
                                   gridspec_kw={"width_ratios": [1, 1.05],
                                                "wspace": 0.55})

    w = plot[plot["block"] == "window_length"].sort_values("realised_days_per_episode_district")
    wf = w[w["arm"] == "fixed_scale"]
    wz = w[w["arm"] == "within_window_z"]
    ax1.axhline(BETA, color=GRAY, lw=1, ls="--")
    ax1.annotate("planted effect", (wf["realised_days_per_episode_district"].iloc[0], BETA),
                 xytext=(2, 4), textcoords="offset points", color=GRAY, fontsize=8)
    ax1.plot(wf["realised_days_per_episode_district"], wf["coef_mean"],
             "o-", color=BLUE, lw=1.4, ms=4, label="regressor in its fixed (built) scale")
    ax1.plot(wz["realised_days_per_episode_district"], wz["coef_mean"],
             "s-", color=RED, lw=1.4, ms=4, label="regressor z-scored within the window")
    for _, row in wz.iterrows():
        ax1.annotate(f"L={int(row['nominal_half_window_days'])}",
                     (row["realised_days_per_episode_district"], row["coef_mean"]),
                     xytext=(0, 6), textcoords="offset points", ha="center",
                     fontsize=7, color=RED)
    ax1.margins(y=0.16)
    ax1.set_xlabel("REALISED days per episode-district\n(not the nominal window label)")
    ax1.set_ylabel("estimated coefficient")
    # Both arms are fitted on the SAME simulated draws, so they move together
    # with the luck of the draw. Only the vertical GAP between them is the
    # artifact; a reader who takes the common slope for a window-length effect
    # is reading Monte Carlo noise.
    ax1.text(0.02, 0.02, "both arms share the same draws:\nonly the GAP is the artifact",
             transform=ax1.transAxes, fontsize=7.5, color=GRAY, va="bottom")
    ax1.set_title("Window length: a weak channel", fontsize=10, loc="left")
    ax1.legend(frameon=False, fontsize=7.5, loc="center left")

    # Bars are s_W, the EXACT distortion — deterministic in the sample
    # definition, no draw involved. The dots are the fitted z-arm means, which
    # are s_W times ordinary sampling noise. Plotting the fitted means alone
    # would draw Monte Carlo error as though it were part of the artifact, and
    # at small --sims the bars would not even be monotone in s_W.
    c = plot[(plot["block"] == "composition")].copy()
    cz = c[c["arm"] == "within_window_z"].sort_values("window_sd_x")
    ypos = np.arange(len(cz))
    ax2.barh(ypos, cz["window_sd_x"], color=RED, alpha=0.8, height=0.6,
             label="scale factor $s_W$ (exact)")
    ax2.plot(cz["coef_over_beta_true"], ypos, "o", color=VIOLET, ms=5, ls="none",
             label=f"fitted coefficient, {args.sims} draws")
    ax2.axvline(1.0, color=GRAY, lw=1, ls="--")
    ax2.annotate("no distortion", (1.0, len(cz) - 0.35), xytext=(4, 0),
                 textcoords="offset points", color=GRAY, fontsize=8)
    ax2.set_yticks(ypos)
    ax2.set_yticklabels(cz["sample_label"], fontsize=8)
    ax2.legend(frameon=False, fontsize=7.5, loc="lower right")
    ax2.set_xlabel("coefficient as a multiple of the planted effect\n"
                   "(same data, same effect, only the sample definition changes)")
    ax2.set_title(f"Sample composition: the strong channel (+/-{PRIMARY_L}d)",
                  fontsize=10, loc="left")

    fig.suptitle("SIMULATED DATA — methods exhibit, not a result. "
                 "The effect is planted; only the sample definition varies.",
                 fontsize=10, y=1.02)
    fig.savefig(OUTPUTS_FIGURES / "zscore_simulation.png", bbox_inches="tight")
    fig.savefig(OUTPUTS_FIGURES / "zscore_simulation.pdf", bbox_inches="tight")
    plt.close(fig)
    print(f"\nsaved {OUTPUTS_FIGURES / 'zscore_simulation.png'} (and .pdf)")

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
print("\n" + "=" * 78)
print("SIMULATED — window length sweep (same episodes, longer windows)")
cols = ["sample_id", "realised_days_per_episode_district", "window_sd_x",
        "arm", "coef_mean", "coef_over_beta_true"]
w = out[(out["block"] == "window_length") & (out["arm"] != "within_window_centred")]
print(w[cols].to_string(index=False))

print("\nSIMULATED — sample composition (same window, different episodes)")
c = out[(out["block"] == "composition") & (out["arm"] != "within_window_centred")]
print(c[cols + ["n_episodes"]].to_string(index=False))

if (out["block"] == "leave_one_episode_out").any():
    loo = out[out["block"] == "leave_one_episode_out"]
    lo_r, hi_r = loo["coef_over_beta_true"].min(), loo["coef_over_beta_true"].max()
    worst = loo.loc[loo["coef_over_beta_true"].idxmin()]
    print(f"\nSIMULATED — leave one episode out ({len(loo)} episodes, analytic, exact):")
    print(f"  the z-scored coefficient ranges {lo_r:.3f}x to {hi_r:.3f}x the planted "
          f"effect ({hi_r / lo_r:.2f}x spread) from dropping ONE episode")
    print(f"  largest single-episode effect: {worst['sample_label']} -> {lo_r:.3f}x")


# The headline is quoted as s_W, which IS the distortion and is exact: it is a
# deterministic function of the sample definition, computed before any fitting.
# coef_mean carries s_W multiplied by ordinary sampling noise in the fixed arm,
# so quoting the fitted ratio as the headline would report the distortion plus
# Monte Carlo error and would move between runs. The fitted spread is printed
# beside it so the two can be compared, not instead of it.
def _span(frame, col):
    return frame[col].min(), frame[col].max(), frame[col].max() / frame[col].min()


zc = out[(out["block"] == "composition") & (out["arm"] == "within_window_z")]
if len(zc) > 1:
    lo_s, hi_s, r_s = _span(zc, "window_sd_x")
    lo_c, hi_c, r_c = _span(zc, "coef_over_beta_true")
    print(f"\nCOMPOSITION (same window, different episodes): the within-window scale "
          f"factor s_W spans {lo_s:.3f} to {hi_s:.3f} ({r_s:.2f}x) — exact, and the "
          f"whole of the distortion. The fitted z-arm coefficients span {lo_c:.3f}x "
          f"to {hi_c:.3f}x the planted effect ({r_c:.2f}x), which is that scale "
          f"factor times ordinary sampling noise in {args.sims} draws.")
wz = out[(out["block"] == "window_length") & (out["arm"] == "within_window_z")]
if len(wz) > 1:
    lo_s, hi_s, r_s = _span(wz, "window_sd_x")
    print(f"WINDOW LENGTH (same episodes, longer windows): s_W spans {lo_s:.3f} to "
          f"{hi_s:.3f} ({r_s:.2f}x) across a realised length running "
          f"{wz['realised_days_per_episode_district'].min():.2f} to "
          f"{wz['realised_days_per_episode_district'].max():.2f} days per "
          f"episode-district. Length is the weak channel; composition is the one "
          f"to report.")
print("=" * 78)
print("Everything above is SIMULATED. Nothing here is an estimate of any effect.")

if failures:
    print("\n" + "!" * 78)
    for f_ in failures:
        print("SELF-CHECK FAILURE:", f_)
    print("!" * 78)
    raise SystemExit(1)
print(f"All {len(CHECKS)} self-checks passed, and all {len(CHECKS)} mutants failed.")
