"""One writer for the provenance register, keyed by source_id.

WHY THIS EXISTS (finding X8)
----------------------------
Seven scripts each wrote data/reference/data_sources.csv with mode="a", so every
re-run appended another row for the same source. The register held 21 rows under
9 distinct IDs — S11 four times, S14/S15/S1b three times each — and every one of
them claimed to be the provenance of the same artifact with a different SHA256.
A register with four answers for one source does not record provenance; it
records that nobody looked.

The rule here is that data_sources.csv is CURRENT STATE: exactly one row per
source_id, describing the artifact that is on disk right now. Superseded rows are
not deleted — they move to data_sources_history.csv, which is append-only. So
"when did this artifact's hash change, and to what" is still answerable, and
"what produced the file I am reading" has exactly one answer.

Both properties are asserted by V.no_duplicate_source_ids in the regression suite.
"""

import ast
import hashlib
import inspect
from datetime import datetime, timezone

from pathlib import Path

import pandas as pd

from config import DATA_REFERENCE, PROJECT_ROOT

SOURCES_LOG = DATA_REFERENCE / "data_sources.csv"
SOURCES_HISTORY = DATA_REFERENCE / "data_sources_history.csv"
COLUMNS = ["source_id", "description", "url", "accessed_utc", "sha256",
           "payload_sha256", "output_file", "generator", "generator_code_sha256"]


def code_fingerprint(script_path):
    """Hash a script's CODE, ignoring comments, docstrings and formatting.

    Recorded alongside each artifact so "was this generated by the current
    version of its script?" has an exact answer.

    An mtime comparison cannot answer it. Every artifact in this repository
    looked stale after one round of comment edits, and a check that cries wolf
    on comments is a check people stop reading. Meanwhile the defect it exists
    to catch was real: 28_build_nyc_attention.py was given the historical-title
    fix and never re-run, so a component was rejected in the paper on numbers
    from a series that was missing Eric Garner entirely (finding T14).

    ast.unparse() normalises whitespace and drops comments; docstrings survive
    it as expression statements, so they are stripped explicitly.
    """
    tree = ast.parse(Path(script_path).read_text())
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef,
                             ast.ClassDef)):
            b = node.body
            if (b and isinstance(b[0], ast.Expr)
                    and isinstance(b[0].value, ast.Constant)
                    and isinstance(b[0].value.value, str)):
                node.body = b[1:] or [ast.Pass()]
    return hashlib.sha256(ast.unparse(tree).encode()).hexdigest()


def _calling_script():
    """The .py file that called log_source, so no call site has to remember."""
    for fr in inspect.stack()[1:]:
        q = Path(fr.filename)
        if q.suffix == ".py" and q.name != "provenance.py" and q.exists():
            return str(q)
    return None


def _rel(path):
    p = Path(path).resolve()
    try:
        return str(p.relative_to(PROJECT_ROOT.resolve()))
    except ValueError:
        return str(p)



def _append_history(rows):
    """Append superseded rows to the append-only history, in the FULL schema.

    The history is written with `header=not exists()`, so its header was fixed
    the first time a row was superseded — when the register had seven columns.
    payload_sha256, generator and generator_code_sha256 were added later and the
    header was never rewritten, so the file carried a 7-column header above 25
    nine-field rows and pandas refused to parse it at all:

        ParserError: Expected 7 fields in line 22, saw 9

    The history is the ONLY record of what an artifact's hash used to be, which
    makes it the only way to notice that a source_id was quietly repointed at a
    different artifact — exactly what happened when the broad basket arm reused
    D1 and S11 and overwrote the strict arm's rows. A history nobody can read is
    the same defect class as a check nobody can fail: it looks like evidence and
    holds none.

    So every append normalises to COLUMNS, and a file whose header is narrower
    than COLUMNS is rewritten once, in place, widening the old rows with empty
    strings rather than inventing values for them.
    """
    rows = rows.reindex(columns=COLUMNS)
    if SOURCES_HISTORY.exists():
        head = SOURCES_HISTORY.read_text().split("\n", 1)[0].split(",")
        if head != COLUMNS:
            old = pd.read_csv(SOURCES_HISTORY, names=COLUMNS, header=None,
                              skiprows=1, engine="python")
            old = old.reindex(columns=COLUMNS)
            pd.concat([old, rows], ignore_index=True).to_csv(
                SOURCES_HISTORY, index=False)
            return
    rows.to_csv(SOURCES_HISTORY, mode="a",
                header=not SOURCES_HISTORY.exists(), index=False)


def log_source(source_id, description, url, payload_bytes=None, out_file=None,
               generator=None):
    """Record (or replace) the provenance row for one source.

    TWO hashes, because they answer different questions and the old single
    column silently answered whichever one the caller happened to pass:

      sha256          the artifact ON DISK. Re-computable from the repository,
                      so it is the one anything can actually verify.
      payload_sha256  the bytes RECEIVED from the endpoint. Not re-computable
                      without re-fetching, and upstream may have changed since,
                      so it is a record of the fetch, never a test.

    Before this split, S7/S8/S10 recorded the payload and S1b/S11-S15 recorded
    the artifact, in one column named "sha256". Anything comparing that column
    to a file would have reported the ACS and MPV artifacts as corrupt.
    """
    gen = generator or _calling_script()
    row = {
        "source_id": source_id,
        "description": description,
        "url": url,
        "accessed_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "sha256": (hashlib.sha256(Path(out_file).read_bytes()).hexdigest()
                   if out_file else ""),
        "payload_sha256": (hashlib.sha256(payload_bytes).hexdigest()
                           if payload_bytes else ""),
        # Repo-relative: an absolute path is a fact about one machine, and a
        # register that a fresh clone cannot resolve cannot be verified.
        "output_file": _rel(out_file) if out_file else "",
        # WHICH script produced this, and a fingerprint of its code at the time.
        "generator": Path(gen).name if gen else "",
        "generator_code_sha256": code_fingerprint(gen) if gen else "",
    }

    cur = pd.read_csv(SOURCES_LOG) if SOURCES_LOG.exists() else pd.DataFrame(columns=COLUMNS)
    superseded = cur[cur["source_id"] == source_id]
    if len(superseded):
        _append_history(superseded)
    keep = cur[cur["source_id"] != source_id]
    out = pd.concat([keep, pd.DataFrame([row])], ignore_index=True)
    out = out.sort_values("source_id", kind="stable")
    out.to_csv(SOURCES_LOG, index=False)

    changed = ""
    if len(superseded) and "sha256" in superseded.columns:
        prev = superseded["sha256"].iloc[-1]
        changed = " (unchanged)" if prev == row["sha256"] else f" (was {str(prev)[:12]})"
    print(f"provenance: {source_id} -> {row['sha256'][:12]}{changed}")
    return row


def relabel_source(source_id, description):
    """Correct a source's DESCRIPTION without claiming a new fetch.

    A description can be wrong about an artifact that is perfectly fine - S11
    asserted a 2015-2024 span while gdelt_news actually ended 2022-12-31
    (finding T7). Re-running log_source would fix the text and also stamp a new
    accessed_utc, asserting a download that did not happen; leaving it alone
    keeps a false statement in the register.

    So this changes the description and NOTHING else. accessed_utc, both hashes
    and the artifact path are untouched, and the superseded row goes to history
    like any other change, so the wording that was there before stays readable.
    """
    if not SOURCES_LOG.exists():
        raise SystemExit("no provenance register to relabel")
    cur = pd.read_csv(SOURCES_LOG)
    hit = cur["source_id"] == source_id
    if not hit.any():
        raise SystemExit(f"{source_id} is not in the register")
    _append_history(cur[hit])
    before = cur.loc[hit, "description"].iloc[0]
    cur.loc[hit, "description"] = description
    cur.to_csv(SOURCES_LOG, index=False)
    print(f"relabelled {source_id}\n  was: {str(before)[:100]}\n  now: {description[:100]}")
