#!/usr/bin/env python3
"""The manuscript's two confirmatory display items, rendered from the sealed files with a claim per number.

    python3 ops/paper_confirmatory_tables.py --out ops/state/paper_tables [--doc docs/PAPER.md] [--start 2000]

Table 1 (two panels): A, the pre-specified primary family — two outcomes × two arms × two strata —
with the first-week mean and its SE, the joint Wald statistic, the randomization p and the
Benjamini–Hochberg-adjusted p; B, the pre-registered reading per stratum (null certified, stratum
rejects, placebo rejects, the pre-freeze minimum detectable effects, the reading).
Table 2: one row per stratum summarising everything outside the family — how many H1-outcome
sensitivity cells were estimated and how many lie at unadjusted p ≤ 0.05, the same for the
falsification cells, the two denominator diagnostics' randomization p, and the secondary arms'
coefficient and asymptotic p.

Every numeric cell registers a claim (template = the row up to the cell, `{}` at the cell) on
data/reference/confirmatory_results.csv or confirmatory_reading.csv; the register replaces the
rows whose note names this script whenever it is re-run (ops/phase_i_tables.py has the same
contract for the supplement's tables).
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
ap = argparse.ArgumentParser()
ap.add_argument("--out", required=True)
ap.add_argument("--doc", default="docs/PAPER.md")
ap.add_argument("--start", type=int, default=2000)
A = ap.parse_args()

RES = "data/reference/confirmatory_results.csv"
RDG = "data/reference/confirmatory_reading.csv"
res = pd.read_csv(ROOT / RES)
rdg = pd.read_csv(ROOT / RDG)
assert (res["data_source"] == "REAL").all(), "the sealed table is not the REAL table"
MINUS = "−"
NOTE = "generated by ops/paper_confirmatory_tables.py"
STRATA = {"C1_clean": "C1", "C2_exposed": "C2", "pooled": "pooled"}
OUT_LABEL = {"edp_share": "EDP share", "edp": "EDP count", "mh_narrow_share": "narrow MH share", "mh_narrow": "narrow MH count"}
ARM_LABEL = {"OLS_share": "share", "PPML_count_offset": "count"}
# H1-outcome sensitivity cells are the ones the reader counts (34: not a falsification family).
NON_H1 = "cardiac|injury|asthma"

claims = []
counter = [A.start]


def fmt(v, f):
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "—"
    return f.format(v).replace("-", MINUS)


def claim(tmpl, artifact, expr, f, slug, name):
    cid = f"C{counter[0]}_{slug}_{name}"
    counter[0] += 1
    claims.append({"claim_id": cid, "source_id": "S1b", "doc": A.doc, "template": tmpl, "artifact": artifact,
                   "expr": expr, "fmt": f, "note": f"Paper table cell ({slug}, {name}); {NOTE}"})


def row(prefix, cells, slug, artifact):
    """cells: list of (text_or_None, [(value, fmt, expr, name), ...]). A cell may hold several numbers
    (mean and SE); each registers its own claim with the other numbers of the cell as literal text."""
    parts = list(prefix)
    for text, nums in cells:
        if text is not None and not nums:
            parts.append(text)
            continue
        rendered = [fmt(v, f) for v, f, _, _ in nums]
        cell = text.format(*rendered) if text else rendered[0]
        for k, (v, f, expr, name) in enumerate(nums):
            if rendered[k] == "—":
                continue
            marks = list(rendered)
            marks[k] = "{}"
            tmpl_cell = text.format(*marks) if text else "{}"
            claim("| " + " | ".join(parts) + " | " + tmpl_cell + " |", artifact, expr, f, slug, name)
        parts.append(cell)
    return "| " + " | ".join(parts) + " |"


def where(stratum, spec, outcome, est, family=None):
    conds = [f"(d.stratum=='{stratum}')", f"(d.spec=='{spec}')", f"(d.outcome=='{outcome}')", f"(d.estimator=='{est}')"]
    if family:
        conds.append(f"(d.family=='{family}')")
    return "d[" + "&".join(conds) + "]"


lines = []
# ---- Table 1A: the family -------------------------------------------------------------------
lines += ["**Table 1 — The pre-specified primary family and its pre-registered reading.** "
          "A: two outcomes × two arms × two strata; first-week mean coefficient (date-clustered SE), the joint Wald "
          "statistic on days 0–7 (8 df), the randomization p at 2,000 draws and the Benjamini–Hochberg-adjusted p over the "
          "family of eight. The test is the joint statistic; the mean is the effect size. B: the reading applied by code "
          "(addendum §23, §19 rule 2): whether the stratum's null was certified, whether it rejects, whether a "
          "falsification cell rejects, the pre-freeze minimum detectable effects for a sustained shift (nominal α; under the "
          "approximate eight-test correction) and for a transient dip-and-rebound, and the sentence the rules return.", "",
          "*A. The family*", "",
          "| stratum | outcome | arm | episodes | first-week mean (SE) | joint χ² | RI p | BH p |", "|---|---|---|---|---|---|---|---|"]
for s in ("C1_clean", "C2_exposed"):
    sl = STRATA[s]
    for col, est in (("edp_share", "OLS_share"), ("edp", "PPML_count_offset"),
                     ("mh_narrow_share", "OLS_share"), ("mh_narrow", "PPML_count_offset")):
        r = res[(res.stratum == s) & (res.spec == "primary") & (res.outcome == col) & (res.estimator == est)].iloc[0]
        w = where(s, "primary", col, est)
        slug = f"t1_{sl}_{col}_{ARM_LABEL[est]}"
        lines.append(row([sl, OUT_LABEL[col], ARM_LABEL[est]], [
            (None, [(int(r.n_episodes), "{}", f"int({w}['n_episodes'].iloc[0])", "episodes")]),
            ("{} ({})", [(r.first_week_mean_coef, "{:.5f}", f"float({w}['first_week_mean_coef'].iloc[0])", "mean"),
                          (r.first_week_mean_se, "{:.5f}", f"float({w}['first_week_mean_se'].iloc[0])", "se")]),
            (None, [(r.first_week_chi2, "{:.2f}", f"float({w}['first_week_chi2'].iloc[0])", "chi2")]),
            (None, [(r.p_randomization, "{:.4f}", f"float({w}['p_randomization'].iloc[0])", "p_ri")]),
            (None, [(r.p_bh_adjusted, "{:.4f}", f"float({w}['p_bh_adjusted'].iloc[0])", "p_bh")]),
        ], slug, RES))
lines += ["", "*B. The reading*", "",
          "| stratum | null certified | stratum rejects | placebo rejects | MDE, sustained (nominal α) | under family correction | MDE, transient | reading |",
          "|---|---|---|---|---|---|---|---|"]
for s in ("C1_clean", "C2_exposed"):
    sl = STRATA[s]
    g = rdg[rdg.stratum == s].set_index("item")["value"]
    def rd(item):
        return f"d[(d.stratum=='{s}')&(d['item']=='{item}')]['value'].iloc[0]"
    yes = {"1": "yes", "0": "no"}
    lines.append(row([sl, yes[str(g["null_certified"])], yes[str(g["stratum_rejects"])], yes[str(g["placebo_rejects_any"])]], [
        (None, [(float(g["mde_level_prefreeze"]), "{:.5f}", f"float({rd('mde_level_prefreeze')})", "mde_level")]),
        (None, [(float(g["mde_level_family_corrected"]), "{:.5f}", f"float({rd('mde_level_family_corrected')})", "mde_corr")]),
        (None, [(float(g["mde_dip_rebound_prefreeze"]), "{:.5f}", f"float({rd('mde_dip_rebound_prefreeze')})", "mde_dip")]),
        (str(g["reading_9_4_input"]), []),   # the reader's own family verdict for the stratum
    ], f"t1b_{sl}", RDG))
concl = rdg[(rdg.stratum == "family") & (rdg["item"] == "conclusion_9_4")]["value"].iloc[0]
lines += ["", f"*Conclusion returned by the reader (note §9.4 as amended by addendum §23): {concl}*", ""]

# ---- Table 2: outside the family, per stratum ---------------------------------------------
lines += ["**Table 2 — Outside the family, per stratum: sensitivities, falsification, the denominator diagnostics and the "
          "secondary arms.** H1-outcome sensitivity cells are the pre-registered sensitivities on the two primary outcomes "
          "and their cancelled-inclusive and EDP-without-EDPM variants, both arms, estimated (cells identical to the primary by "
          "construction are not counted); falsification cells are the cardiac and asthma shares and counts, and their "
          "coverage-clean variants, plus injury. Counts at p ≤ 0.05 use the unadjusted randomization p. The denominator "
          "diagnostics are the raw EDP count without an offset and total dispatches (randomization p). The dose-response arm is "
          "the first-week effect on the share per SD of the episode's peak intensity, asymptotic p only; the B-HEARD "
          "interaction exists in C2 only. The pooled row is descriptive.", "",
          "| stratum | H1-outcome sensitivity cells | at p ≤ 0.05 | falsification cells | at p ≤ 0.05 | raw EDP count, RI p | total dispatches, RI p | dose-response, EDP share: coef (asymptotic p) | dose-response, narrow MH share: coef (p) | B-HEARD interaction, EDP share: coef (p) |",
          "|---|---|---|---|---|---|---|---|---|---|"]
H1 = f"(~d.outcome.str.contains('{NON_H1}'))"
for s in ("C1_clean", "C2_exposed", "pooled"):
    sl = STRATA[s]
    sens = res[(res.stratum == s) & (res.family == "sensitivity") & (res.status.str.startswith("OK"))]
    h1 = sens[~sens.outcome.str.contains(NON_H1)]
    pl = res[(res.stratum == s) & (res.family == "placebo") & (res.status.str.startswith("OK"))]
    base = f"(d.stratum=='{s}')&(d.status.str.startswith('OK'))"
    n_h1 = f"int((d[{base}&(d.family=='sensitivity')&{H1}]).shape[0])"
    k_h1 = f"int((d[{base}&(d.family=='sensitivity')&{H1}]['p_randomization']<=0.05).sum())"
    n_pl = f"int((d[{base}&(d.family=='placebo')]).shape[0])"
    k_pl = f"int((d[{base}&(d.family=='placebo')]['p_randomization']<=0.05).sum())"
    raw = res[(res.stratum == s) & (res.family == "diagnostic") & (res.outcome == "edp")].iloc[0]
    tot = res[(res.stratum == s) & (res.family == "diagnostic") & (res.outcome == "total_calls")].iloc[0]
    raw_w = f"d[(d.stratum=='{s}')&(d.family=='diagnostic')&(d.outcome=='edp')]"
    tot_w = f"d[(d.stratum=='{s}')&(d.family=='diagnostic')&(d.outcome=='total_calls')]"
    def dose(outcome):
        q = res[(res.stratum == s) & (res.spec == "dose_response") & (res.outcome == outcome)]
        if q.empty:
            return ("—", [])
        q = q.iloc[0]
        w = where(s, "dose_response", outcome, q.estimator)
        return ("{} ({})", [(q.first_week_mean_coef, "{:.5f}", f"float({w}['first_week_mean_coef'].iloc[0])", f"dose_{outcome}_coef"),
                            (q.p_asymptotic, "{:.4f}", f"float({w}['p_asymptotic'].iloc[0])", f"dose_{outcome}_p")])
    bh = res[(res.stratum == s) & (res.spec == "bheard_interaction") & (res.outcome == "edp_share")]
    if bh.empty:
        bh_cell = ("—", [])
    else:
        b = bh.iloc[0]
        w = where(s, "bheard_interaction", "edp_share", b.estimator)
        bh_cell = ("{} ({})", [(b.first_week_mean_coef, "{:.5f}", f"float({w}['first_week_mean_coef'].iloc[0])", "bheard_coef"),
                               (b.p_asymptotic, "{:.4f}", f"float({w}['p_asymptotic'].iloc[0])", "bheard_p")])
    lines.append(row([sl + (" (descriptive)" if s == "pooled" else "")], [
        (None, [(len(h1), "{}", n_h1, "n_h1")]),
        (None, [(int((h1.p_randomization <= 0.05).sum()), "{}", k_h1, "k_h1")]),
        (None, [(len(pl), "{}", n_pl, "n_pl")]),
        (None, [(int((pl.p_randomization <= 0.05).sum()), "{}", k_pl, "k_pl")]),
        (None, [(raw.p_randomization, "{:.4f}", f"float({raw_w}['p_randomization'].iloc[0])", "raw_edp_p")]),
        (None, [(tot.p_randomization, "{:.4f}", f"float({tot_w}['p_randomization'].iloc[0])", "total_p")]),
        dose("edp_share"), dose("mh_narrow_share"), bh_cell,
    ], f"t2_{sl}", RES))
lines.append("")

out = ROOT / A.out
out.mkdir(parents=True, exist_ok=True)
(out / "tables.md").write_text("\n".join(lines), encoding="utf-8")
with open(out / "claims.csv", "w", newline="", encoding="utf-8") as fh:
    w = csv.DictWriter(fh, fieldnames=["claim_id", "source_id", "doc", "template", "artifact", "expr", "fmt", "note"], lineterminator="\r\n")
    w.writeheader(); w.writerows(claims)
dup = pd.Series([c["template"] for c in claims]).duplicated().sum()
print(f"wrote {out/'tables.md'} ({len(lines)} lines) and {out/'claims.csv'} ({len(claims)} rows; next free id C{counter[0]}); duplicate templates: {dup}")
