#!/usr/bin/env python3
"""The manuscript's two confirmatory display items, rendered from the sealed files with a claim per number.

    python3 ops/paper_confirmatory_tables.py --out ops/state/paper_tables [--doc docs/PAPER.md] [--start 2000]

Table 1 (two panels): A, the pre-specified primary family — two outcomes × two arms × two strata —
with the first-week mean, its SE and the normal-approximation 95% interval on that SE, the joint
Wald statistic, the randomization p, the asymptotic p reported beside it, and the
Benjamini–Hochberg-adjusted p; B, per stratum, the episodes and district-day observations behind
the estimates and the pre-registered reading (null certified, stratum rejects, falsification
outcome rejects, the pre-freeze minimum detectable effects, the reading).
Table 2 (two panels): A, per stratum, the H1-outcome sensitivity cells — how many were estimated,
how many lie at unadjusted p ≤ 0.05, the range of their randomization p and of their share-arm
first-week means — and the falsification cells split into the four override cells (cardiac and
asthma) and the two injury cells; B, the two denominator diagnostics' first-week means with their
randomization p, and the secondary arms' coefficient and asymptotic p. The referee panel of
2026-09-21 asked for the intervals, the asymptotic p, the coefficients beside the diagnostics'
p-values and the ranges in place of a bare tally; all are arithmetic on the sealed table.

Every numeric cell registers a claim (template = the row up to the cell, `{}` at the cell) on
data/reference/confirmatory_results.csv or confirmatory_reading.csv; the register replaces the
rows whose note names this script whenever it is re-run (ops/phase_i_tables.py has the same
contract for the supplement's tables).
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
ap = argparse.ArgumentParser()
ap.add_argument("--out", required=True)
ap.add_argument("--doc", default="docs/PAPER.md")
ap.add_argument("--start", type=int, default=2000)
A = ap.parse_args()

RES = "data/reference/confirmatory_results.csv"
RDG = "data/reference/confirmatory_reading.csv"
res = pd.read_csv(ROOT / RES)
rdg = pd.read_csv(ROOT / RDG)
assert (res["data_source"] == "REAL").all(), "the sealed table is not the REAL table"
MINUS = "−"
NOTE = "generated by ops/paper_confirmatory_tables.py"
STRATA = {"C1_clean": "C1", "C2_exposed": "C2", "pooled": "pooled"}
OUT_LABEL = {"edp_share": "EDP share", "edp": "EDP count", "mh_narrow_share": "narrow mental-health share",
             "mh_narrow": "narrow mental-health count"}
ARM_LABEL = {"OLS_share": "share", "PPML_count_offset": "count"}
# H1-outcome sensitivity cells are the ones the reader counts (34: not a falsification family).
NON_H1 = "cardiac|injury|asthma"

claims = []
counter = [A.start]


def fmt(v, f):
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "—"
    return f.format(v).replace("-", MINUS)


def claim(tmpl, artifact, expr, f, slug, name):
    cid = f"C{counter[0]}_{slug}_{name}"
    counter[0] += 1
    claims.append({"claim_id": cid, "source_id": "S1b", "doc": A.doc, "template": tmpl, "artifact": artifact,
                   "expr": expr, "fmt": f, "note": f"Paper table cell ({slug}, {name}); {NOTE}"})


def row(prefix, cells, slug, artifact):
    """cells: list of (text_or_None, [(value, fmt, expr, name), ...]). A cell may hold several numbers
    (mean and SE); each registers its own claim with the other numbers of the cell as literal text."""
    parts = list(prefix)
    for text, nums in cells:
        if text is not None and not nums:
            parts.append(text)
            continue
        rendered = [fmt(v, f) for v, f, _, _ in nums]
        cell = text.format(*rendered) if text else rendered[0]
        for k, (v, f, expr, name) in enumerate(nums):
            if rendered[k] == "—":
                continue
            marks = list(rendered)
            marks[k] = "{}"
            tmpl_cell = text.format(*marks) if text else "{}"
            claim("| " + " | ".join(parts) + " | " + tmpl_cell + " |", artifact, expr, f, slug, name)
        parts.append(cell)
    return "| " + " | ".join(parts) + " |"


def where(stratum, spec, outcome, est, family=None):
    conds = [f"(d.stratum=='{stratum}')", f"(d.spec=='{spec}')", f"(d.outcome=='{outcome}')", f"(d.estimator=='{est}')"]
    if family:
        conds.append(f"(d.family=='{family}')")
    return "d[" + "&".join(conds) + "]"


lines = []
# ---- Table 1A: the family -------------------------------------------------------------------
lines += ["**Table 1 — The pre-specified primary family and its pre-registered reading, New York City community "
          "districts, confirmation periods C1 (July 2015–December 2016 and January–May 2021, before B-HEARD) and C2 "
          "(June 2021–December 2024, during the B-HEARD rollout).** A: two outcomes × two arms × two periods. The "
          "first-week mean is the average of the eight daily coefficients for days 0–7 relative to the day before the "
          "episode began, with its standard error clustered on the calendar date and the normal-approximation 95% "
          "interval on that standard error (mean ± 1.96 SE); it is the reported effect size and not the test. The test "
          "is the joint Wald statistic that all eight coefficients are zero (8 df), with its randomization p at 2,000 "
          "placebo draws (primary), the asymptotic p beside it (anti-conservative on these data; S1.6) and the "
          "Benjamini–Hochberg-adjusted p over the family of eight. Shares are fractions of a district-day's dispatches; "
          "counts are log points under a total-dispatch offset. B: the pre-registered rules applied by code to the "
          "sealed table (verbatim output in S2): the episodes and district-day observations behind each period's "
          "estimates, whether the randomization null was certified (the certificate covers the share arm on the EDP share "
          "without the covariate; S1.6), whether the period rejects on either outcome under the two-arms rule, whether a "
          "cardiac or asthma cell rejects, the pre-freeze minimum detectable effects at 80% power for a sustained "
          "first-week shift (at nominal α, and inflated by the plan's approximate one-parameter factor of 1.28 for a "
          "Bonferroni-style α/8; the factor matched to the eight-df statistic is 1.21, and both are upper bounds on a "
          "Benjamini–Hochberg correction) and for a dip-and-rebound, and the reading the rules return.", "",
          "*A. The family*", "",
          "| period | outcome | arm | first-week mean (SE) | interval (95%) | joint χ² (8 df) | randomization p | asymptotic p | BH-adjusted p |",
          "|---|---|---|---|---|---|---|---|---|"]
for s in ("C1_clean", "C2_exposed"):
    sl = STRATA[s]
    for col, est in (("edp_share", "OLS_share"), ("edp", "PPML_count_offset"),
                     ("mh_narrow_share", "OLS_share"), ("mh_narrow", "PPML_count_offset")):
        r = res[(res.stratum == s) & (res.spec == "primary") & (res.outcome == col) & (res.estimator == est)].iloc[0]
        w = where(s, "primary", col, est)
        slug = f"t1_{sl}_{col}_{ARM_LABEL[est]}"
        lo = r.first_week_mean_coef - 1.96 * r.first_week_mean_se
        hi = r.first_week_mean_coef + 1.96 * r.first_week_mean_se
        lines.append(row([sl, OUT_LABEL[col], ARM_LABEL[est]], [
            ("{} ({})", [(r.first_week_mean_coef, "{:.5f}", f"float({w}['first_week_mean_coef'].iloc[0])", "mean"),
                          (r.first_week_mean_se, "{:.5f}", f"float({w}['first_week_mean_se'].iloc[0])", "se")]),
            ("{} to {}", [(lo, "{:.4f}", f"float({w}['first_week_mean_coef'].iloc[0]-1.96*{w}['first_week_mean_se'].iloc[0])", "ci_lo"),
                          (hi, "{:.4f}", f"float({w}['first_week_mean_coef'].iloc[0]+1.96*{w}['first_week_mean_se'].iloc[0])", "ci_hi")]),
            (None, [(r.first_week_chi2, "{:.2f}", f"float({w}['first_week_chi2'].iloc[0])", "chi2")]),
            (None, [(r.p_randomization, "{:.4f}", f"float({w}['p_randomization'].iloc[0])", "p_ri")]),
            (None, [(r.p_asymptotic, "{:.4f}", f"float({w}['p_asymptotic'].iloc[0])", "p_asy")]),
            (None, [(r.p_bh_adjusted, "{:.4f}", f"float({w}['p_bh_adjusted'].iloc[0])", "p_bh")]),
        ], slug, RES))
lines += ["", "*B. The reading*", "",
          "| period | episodes | district-day observations | null certified (share arm, EDP share) | period rejects | falsification outcome rejects | minimum detectable effect, sustained shift (nominal α) | × 1.28 (α/8, one-parameter) | minimum detectable effect, dip-and-rebound | reading |",
          "|---|---|---|---|---|---|---|---|---|---|"]
for s in ("C1_clean", "C2_exposed"):
    sl = STRATA[s]
    g = rdg[rdg.stratum == s].set_index("item")["value"]
    prim = res[(res.stratum == s) & (res.spec == "primary") & (res.outcome == "edp_share") & (res.estimator == "OLS_share")].iloc[0]
    wp = where(s, "primary", "edp_share", "OLS_share")
    def rd(item):
        return f"d[(d.stratum=='{s}')&(d['item']=='{item}')]['value'].iloc[0]"
    yes = {"1": "yes", "0": "no"}
    # the two counts come from the sealed table, the reading from the reader's file: two artifacts, so two rows
    counts = row([sl + ", primary family"], [
        (None, [(int(prim.n_episodes), "{}", f"int({wp}['n_episodes'].iloc[0])", "episodes")]),
        (None, [(int(prim.n_obs), "{:,}", f"int({wp}['n_obs'].iloc[0])", "n_obs")]),
    ], f"t1b_{sl}", RES)
    reading = row([sl + ", primary family", str(int(prim.n_episodes)), f"{int(prim.n_obs):,}",
                   yes[str(g["null_certified"])], yes[str(g["stratum_rejects"])], yes[str(g["placebo_rejects_any"])]], [
        (None, [(float(g["mde_level_prefreeze"]), "{:.5f}", f"float({rd('mde_level_prefreeze')})", "mde_level")]),
        (None, [(float(g["mde_level_family_corrected"]), "{:.5f}", f"float({rd('mde_level_family_corrected')})", "mde_corr")]),
        (None, [(float(g["mde_dip_rebound_prefreeze"]), "{:.5f}", f"float({rd('mde_dip_rebound_prefreeze')})", "mde_dip")]),
        (str(g["reading_9_4_input"]), []),   # the rules' own verdict for the period
    ], f"t1b_{sl}", RDG)
    assert reading.startswith(counts.rstrip(" |")), (counts, reading)
    lines.append(reading)
lines.append("")

# ---- Table 2: outside the family, per stratum ---------------------------------------------
lines += ["**Table 2 — Outside the primary family, per period: the pre-registered sensitivities, the falsification "
          "outcomes, the denominator diagnostics and the secondary arms.** A: H1-outcome sensitivity cells are the "
          "pre-registered sensitivities on the two primary outcomes (and their cancelled-inclusive and EDP-without-EDPM "
          "variants), both arms, that were estimated — a cell identical to the primary by construction is not counted, so "
          "the two periods' batteries differ (C1's basket and EDP-without-EDPM branches are identical to its primary; C1 has "
          "no B-HEARD-bound branch). They re-estimate the same four primary cells on overlapping samples and are one "
          "result seen many times, not independent tests: the tally counts cells at unadjusted randomization p ≤ 0.05, and "
          "the ranges show that no share-arm first-week mean moves away from zero (every cell is Table S4). Override "
          "cells are the cardiac and asthma shares and counts in the primary specification, four per period; one at "
          "unadjusted randomization p ≤ 0.05 would have voided the period's primary rejections. Injury is reported "
          "beside them as a marker of street activity and does not override; the coverage-clean variants of all three "
          "are in Table S4 and none reaches p ≤ 0.05. B: the denominator diagnostics are the raw EDP count without an "
          "offset and total dispatches, first-week mean in log points with the randomization p of the joint test. The "
          "dose-response arm is the first-week effect on the share per standard deviation of the episode's peak intensity, "
          "asymptotic p only; the B-HEARD interaction exists in C2 only. The pooled rows are descriptive.", "",
          "*A. Sensitivities and falsification outcomes*", "",
          "| period | H1-outcome sensitivity cells | at p ≤ 0.05 | randomization p, range | first-week mean, share arm, range | override cells (cardiac, asthma) | at p ≤ 0.05 | injury cells | at p ≤ 0.05 |",
          "|---|---|---|---|---|---|---|---|---|"]
H1 = f"(~d.outcome.str.contains('{NON_H1}'))"
panel_b = []
for s in ("C1_clean", "C2_exposed", "pooled"):
    sl = STRATA[s]
    sens = res[(res.stratum == s) & (res.family == "sensitivity") & (res.status.str.startswith("OK"))]
    h1 = sens[~sens.outcome.str.contains(NON_H1)]
    h1s = h1[h1.estimator == "OLS_share"]
    pl = res[(res.stratum == s) & (res.family == "placebo") & (res.status.str.startswith("OK"))]
    ov = pl[pl.outcome.str.contains("cardiac|asthma")]
    inj = pl[pl.outcome.str.contains("injury")]
    base = f"(d.stratum=='{s}')&(d.status.str.startswith('OK'))"
    h1w = f"d[{base}&(d.family=='sensitivity')&{H1}]"
    h1sw = f"d[{base}&(d.family=='sensitivity')&{H1}&(d.estimator=='OLS_share')]"
    ovw = f"d[{base}&(d.family=='placebo')&(d.outcome.str.contains('cardiac|asthma'))]"
    injw = f"d[{base}&(d.family=='placebo')&(d.outcome.str.contains('injury'))]"
    label = sl + (" (descriptive)" if s == "pooled" else "")
    lines.append(row([label], [
        (None, [(len(h1), "{}", f"int(({h1w}).shape[0])", "n_h1")]),
        (None, [(int((h1.p_randomization <= 0.05).sum()), "{}", f"int(({h1w}['p_randomization']<=0.05).sum())", "k_h1")]),
        ("{} to {}", [(h1.p_randomization.min(), "{:.4f}", f"float({h1w}['p_randomization'].min())", "p_min"),
                      (h1.p_randomization.max(), "{:.4f}", f"float({h1w}['p_randomization'].max())", "p_max")]),
        ("{} to {}", [(h1s.first_week_mean_coef.min(), "{:.5f}", f"float({h1sw}['first_week_mean_coef'].min())", "share_min"),
                      (h1s.first_week_mean_coef.max(), "{:.5f}", f"float({h1sw}['first_week_mean_coef'].max())", "share_max")]),
        (None, [(len(ov), "{}", f"int(({ovw}).shape[0])", "n_override")]),
        (None, [(int((ov.p_randomization <= 0.05).sum()), "{}", f"int(({ovw}['p_randomization']<=0.05).sum())", "k_override")]),
        (None, [(len(inj), "{}", f"int(({injw}).shape[0])", "n_injury")]),
        (None, [(int((inj.p_randomization <= 0.05).sum()), "{}", f"int(({injw}['p_randomization']<=0.05).sum())", "k_injury")]),
    ], f"t2_{sl}", RES))
    raw = res[(res.stratum == s) & (res.family == "diagnostic") & (res.outcome == "edp")].iloc[0]
    tot = res[(res.stratum == s) & (res.family == "diagnostic") & (res.outcome == "total_calls")].iloc[0]
    raw_w = f"d[(d.stratum=='{s}')&(d.family=='diagnostic')&(d.outcome=='edp')]"
    tot_w = f"d[(d.stratum=='{s}')&(d.family=='diagnostic')&(d.outcome=='total_calls')]"
    def dose(outcome):
        q = res[(res.stratum == s) & (res.spec == "dose_response") & (res.outcome == outcome)]
        if q.empty:
            return ("—", [])
        q = q.iloc[0]
        w = where(s, "dose_response", outcome, q.estimator)
        return ("{} ({})", [(q.first_week_mean_coef, "{:.5f}", f"float({w}['first_week_mean_coef'].iloc[0])", f"dose_{outcome}_coef"),
                            (q.p_asymptotic, "{:.4f}", f"float({w}['p_asymptotic'].iloc[0])", f"dose_{outcome}_p")])
    bh = res[(res.stratum == s) & (res.spec == "bheard_interaction") & (res.outcome == "edp_share")]
    if bh.empty:
        bh_cell = ("—", [])
    else:
        b = bh.iloc[0]
        w = where(s, "bheard_interaction", "edp_share", b.estimator)
        bh_cell = ("{} ({})", [(b.first_week_mean_coef, "{:.5f}", f"float({w}['first_week_mean_coef'].iloc[0])", "bheard_coef"),
                               (b.p_asymptotic, "{:.4f}", f"float({w}['p_asymptotic'].iloc[0])", "bheard_p")])
    panel_b.append(row([label], [
        ("{} ({})", [(raw.first_week_mean_coef, "{:.5f}", f"float({raw_w}['first_week_mean_coef'].iloc[0])", "raw_edp_coef"),
                      (raw.p_randomization, "{:.4f}", f"float({raw_w}['p_randomization'].iloc[0])", "raw_edp_p")]),
        ("{} ({})", [(tot.first_week_mean_coef, "{:.5f}", f"float({tot_w}['first_week_mean_coef'].iloc[0])", "total_coef"),
                      (tot.p_randomization, "{:.4f}", f"float({tot_w}['p_randomization'].iloc[0])", "total_p")]),
        dose("edp_share"), dose("mh_narrow_share"), bh_cell,
    ], f"t2b_{sl}", RES))
lines += ["", "*B. Denominator diagnostics and secondary arms*", "",
          "| period | raw EDP count, no offset: first-week mean (randomization p) | total dispatches: first-week mean (randomization p) | dose-response, EDP share: coefficient per SD (asymptotic p) | dose-response, narrow mental-health share: coefficient (p) | B-HEARD interaction, EDP share: coefficient (p) |",
          "|---|---|---|---|---|---|"]
lines += panel_b
lines.append("")

out = ROOT / A.out
out.mkdir(parents=True, exist_ok=True)
(out / "tables.md").write_text("\n".join(lines), encoding="utf-8")
with open(out / "claims.csv", "w", newline="", encoding="utf-8") as fh:
    w = csv.DictWriter(fh, fieldnames=["claim_id", "source_id", "doc", "template", "artifact", "expr", "fmt", "note"], lineterminator="\r\n")
    w.writeheader(); w.writerows(claims)
dup = pd.Series([c["template"] for c in claims]).duplicated().sum()
print(f"wrote {out/'tables.md'} ({len(lines)} lines) and {out/'claims.csv'} ({len(claims)} rows; next free id C{counter[0]}); duplicate templates: {dup}")
