"""Table 1 of the paper — the episode list — rendered from its artifacts, never typed.

Treatment-side only: the rebuilt episode list (the one the models use), the frozen
pre-registration list (kept byte-identical), and the stratum each episode can be
tested in under first-week containment (event_study.stratum_episodes). No outcome
row is read, so this runs under the freeze.

Writes docs/tables/TABLE1_episodes.md. The file is generated, so the register's
rule that every number in a paper table carries a claim is met differently here:
the regression suite (V.table1_regenerates) re-renders the table from the same
inputs and requires the committed bytes to match. Edit the inputs or this
renderer; never the table.

    python3 ops/paper_table1.py            # write docs/tables/TABLE1_episodes.md
    python3 ops/paper_table1.py --check    # exit 1 if the committed file is stale
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from config import (CONFIRMATION_ANALYSIS_WINDOWS, DATA_REFERENCE, DISCOVERY_END,  # noqa: E402
                    DISCOVERY_START, EPISODE_LIST_PRIMARY, EVENT_WINDOW_POST, EVENT_WINDOW_PRE)
from event_study import stratum_episodes  # noqa: E402

REBUILT = DATA_REFERENCE / EPISODE_LIST_PRIMARY
FROZEN = DATA_REFERENCE / "confirmation_episodes.csv"
OUT = ROOT / "docs" / "tables" / "TABLE1_episodes.md"
MATCH_DAYS = 7   # a frozen episode starting within this many days is the same burst


def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()[:12]


def render():
    ep = pd.read_csv(REBUILT, parse_dates=["start", "end", "peak_date"])
    ep = ep.sort_values("start").reset_index(drop=True)          # every episode, discovery included
    fz = pd.read_csv(FROZEN, parse_dates=["start", "end"])
    fz = fz.sort_values("start").reset_index(drop=True)

    strata = {"discovery": [(DISCOVERY_START, DISCOVERY_END)],
              "C1": [CONFIRMATION_ANALYSIS_WINDOWS[0], CONFIRMATION_ANALYSIS_WINDOWS[1]],
              "C2": [CONFIRMATION_ANALYSIS_WINDOWS[2]]}
    label = {}
    for name, wins in strata.items():
        kept, _ = stratum_episodes(ep["start"], wins, EVENT_WINDOW_PRE, EVENT_WINDOW_POST)
        for k in kept:
            tail = k.get("days_outside_full_window", 0)
            label[pd.Timestamp(k["start"])] = name + (f" (tails truncated {tail} d)" if tail else "")
    frozen_starts = fz["start"].tolist()

    def nearest_frozen(s):
        if not frozen_starts:
            return "—", None
        d = min(frozen_starts, key=lambda f: abs((f - s).days))
        off = (d - s).days
        return (d.date().isoformat(), off) if abs(off) <= MATCH_DAYS else ("—", None)

    lines = [
        "# Table 1 — Attention episodes under the adopted shock rule, with the frozen list beside them",
        "",
        f"*Generated by `ops/paper_table1.py` from `{REBUILT.relative_to(ROOT)}` "
        f"(sha256 {sha(REBUILT)}…) and `{FROZEN.relative_to(ROOT)}` (sha256 {sha(FROZEN)}…). "
        "Do not edit: `V.table1_regenerates` re-renders it and fails on any difference.*",
        "",
        "An episode is a burst of attention to police violence, not a killing: the "
        "\"driver\" column names the articles whose pageviews carry the burst, with the "
        "share of the burst each carries, and the \"candidate events\" column names the "
        "registry deaths in the 60-day lookback. The stratum is where the episode's "
        "day −1 to day +7 lies (first-week containment); the discovery stratum was "
        "explored, C1 and C2 were sealed until the confirmatory run. The frozen "
        f"column gives the start date of the pre-registered list's episode within ±{MATCH_DAYS} days, "
        "and its offset in days, or — when the adopted rule found a burst the frozen "
        "regime rule did not resolve.",
        "",
        "| # | start | end | high days | peak | peak index (SD) | candidate events (registry, 60-day lookback) | drivers (share of burst) | stratum | frozen start (offset) |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in ep.itertuples():
        fs, off = nearest_frozen(r.start)
        frozen_cell = "—" if off is None else f"{fs} ({off:+d})"
        strat = label.get(pd.Timestamp(r.start), "none (first week outside every analysis window)")
        lines.append("| " + " | ".join([
            str(r.episode), r.start.date().isoformat(), r.end.date().isoformat(), str(int(r.n_high_days)),
            r.peak_date.date().isoformat(), f"{r.peak_cai_d:.2f}",
            str(r.candidate_events) if pd.notna(r.candidate_events) else "—",
            str(r.drivers) if pd.notna(r.drivers) else "—", strat, frozen_cell]) + " |")
    # the other half of the diff: frozen episodes with no adopted counterpart
    adopted = ep["start"].tolist()
    orphans = [f for f in fz.itertuples() if min(abs((f.start - a).days) for a in adopted) > MATCH_DAYS]
    n_c = {n: sum(1 for v in label.values() if v.startswith(n)) for n in strata}
    lines += ["",
              f"**Counts.** {len(ep)} adopted episodes: {n_c['discovery']} discovery, {n_c['C1']} C1, "
              f"{n_c['C2']} C2, {len(ep) - sum(n_c.values())} in no analysis window. "
              f"{len(fz)} frozen episodes, of which {len(orphans)} have no adopted episode within ±{MATCH_DAYS} days:",
              ""]
    if orphans:
        lines += ["| frozen # | start | end | high days | peak | peak index (SD) | candidate events |",
                  "|---|---|---|---|---|---|---|"]
        for f in orphans:
            lines.append("| " + " | ".join([
                str(f.episode), f.start.date().isoformat(), f.end.date().isoformat(), str(int(f.n_high_days)),
                pd.Timestamp(f.peak_date).date().isoformat(), f"{f.peak_cai_d:.2f}",
                str(f.candidate_events) if pd.notna(f.candidate_events) else "—"]) + " |")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text = render()
    if a.check:
        if not OUT.exists():
            print(f"{OUT} absent"); sys.exit(1)
        ok = OUT.read_text() == text
        print("up to date" if ok else "STALE: committed table differs from a fresh render")
        sys.exit(0 if ok else 1)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    print(f"wrote {OUT} ({len(text.splitlines())} lines)")
