#!/usr/bin/env python3
"""Copy the manuscript's figures from outputs/figures (gitignored, regenerated by 08_figures.py
and 25_zscore_simulation.py) into docs/figures (tracked), with a sha256 manifest.

    python3 ops/paper_figures.py           # copy and write docs/figures/MANIFEST.json
    python3 ops/paper_figures.py --check   # exit 1 if any tracked figure differs from the current output

The pipeline is deterministic to the byte (finding X20), so a tracked figure that differs from a
fresh output means either the inputs changed or the copy is stale; V.paper_figures_current runs
the same comparison inside the gate.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "outputs" / "figures"
DST = ROOT / "docs" / "figures"
FIGURES = ["fig1_raw_series.png", "fig2_irf_primary.png", "fig3_windows.png", "fig4_decomposition.png",
           "fig5_bridge.png", "fig6_conf_paths_edp.png", "fig6b_conf_paths_mh.png", "fig7_attention_decade.png",
           "zscore_simulation.png"]


def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def compare():
    """(missing_outputs, stale_or_missing_copies, up_to_date)"""
    missing, stale, ok = [], [], []
    for f in FIGURES:
        s, d = SRC / f, DST / f
        if not s.exists():
            missing.append(f); continue
        if not d.exists() or sha(s) != sha(d):
            stale.append(f)
        else:
            ok.append(f)
    return missing, stale, ok


if __name__ == "__main__":
    if "--check" in sys.argv:
        missing, stale, ok = compare()
        print(f"up to date: {ok}; stale or uncopied: {stale}; no current output: {missing}")
        sys.exit(1 if stale else 0)
    DST.mkdir(parents=True, exist_ok=True)
    manifest = {}
    for f in FIGURES:
        s = SRC / f
        if not s.exists():
            print(f"skip {f}: no current output"); continue
        (DST / f).write_bytes(s.read_bytes()); manifest[f] = sha(s)
    (DST / "MANIFEST.json").write_text(json.dumps(manifest, indent=1) + "\n")
    print(f"copied {len(manifest)} figure(s) into {DST.relative_to(ROOT)}")
