"""Render the confirmatory result tables and the claim rows that hold every cell.

Reads the sealed result (30) and its mechanical reading (34) and writes, into an
output directory the author names, (a) `tables.md` — the Markdown tables for
PAPER_MASTER §8b and PAPER.md's confirmatory Results, and (b) `claims.csv` — one
CLAIMS_REGISTER row per numeric cell, each template anchored on its own row so
that `V.claims_cover_exhibits` and `V.claims_reproduce` hold the table to the
artifact. Nothing here writes into docs/: the author pastes the tables and
appends the rows, then runs 31 --claims-only.

    python3 ops/phase_i_tables.py --out ops/state/phase_i_tables [--synthetic] [--start 210]

Synthetic mode reads the dry run and its reading and exists to exercise the
renderer; its output says nothing about any hypothesis and must not be pasted.
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from config import H1_OUTCOMES  # noqa: E402
from event_study import count_outcome  # noqa: E402

ap = argparse.ArgumentParser()
ap.add_argument("--out", required=True)
ap.add_argument("--synthetic", action="store_true")
ap.add_argument("--start", type=int, default=210, help="first claim number to issue")
ap.add_argument("--docs", nargs="+", default=["docs/PAPER_MASTER.md"],
                help="documents the claims address (one row set per document)")
A = ap.parse_args()

if A.synthetic:
    RES = "outputs/tables/confirmatory_results_dryrun_synthetic.csv"
    RDG = "outputs/tables/confirmatory_reading_dryrun_synthetic.csv"
else:
    RES = "data/reference/confirmatory_results.csv"
    RDG = "data/reference/confirmatory_reading.csv"
res = pd.read_csv(ROOT / RES)
rdg = pd.read_csv(ROOT / RDG)
if A.synthetic and not (res["data_source"] == "SYNTHETIC").all():
    raise SystemExit("synthetic mode on a non-synthetic table")
if not A.synthetic and not (res["data_source"] == "REAL").all():
    raise SystemExit("real mode on a non-REAL table")

MINUS = "−"
STRATA = {"C1_clean": "C1", "C2_exposed": "C2", "pooled": "pooled"}
OUT_LABEL = {"edp_share": "EDP share", "edp": "EDP count", "mh_narrow_share": "narrow MH share",
             "mh_narrow": "narrow MH count", "cardiac_share": "cardiac share", "cardiac": "cardiac count",
             "injury_share": "injury share", "injury": "injury count", "asthma_share": "asthma share",
             "asthma": "asthma count", "total_calls": "total dispatches"}
ARM_LABEL = {"OLS_share": "share", "PPML_count_offset": "count", "PPML_count_no_offset": "count, no offset"}
SPEC_LABEL = {"sens_drop_jul2016": "drop July 2016", "sens_broad_basket": "broad basket",
              "sens_spliced_wiki": "spliced Wikipedia series", "sens_coverage_clean": "coverage-clean",
              "sens_bheard_late_bound": "late B-HEARD bound"}

claims = []
counter = [A.start]


def fmt_num(v, f):
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "—"
    s = f.format(v)
    return s.replace("-", MINUS)


def where(stratum, spec, outcome, estimator, family=None):
    conds = [f"(d.stratum=='{stratum}')", f"(d.spec=='{spec}')", f"(d.outcome=='{outcome}')",
             f"(d.estimator=='{estimator}')"]
    if family:
        conds.append(f"(d.family=='{family}')")
    return "d[" + "&".join(conds) + "]"


def cells_for(row, defs):
    """defs: list of (label, value, fmt, expr) per numeric cell; returns rendered cells and
    registers one claim per numeric cell whose template is the row up to that cell."""
    rendered = []
    return rendered


def emit_row(prefix_cells, num_cells, slug, artifact):
    """prefix_cells: text cells; num_cells: list of (value, fmt, expr, name). Writes the
    row and one claim per numeric cell, template anchored on everything before it."""
    parts = list(prefix_cells)
    for value, f, expr, name in num_cells:
        text = fmt_num(value, f)
        if text != "—":
            tmpl = "| " + " | ".join(parts) + " | {} |"
            cid = f"C{counter[0]}_{slug}_{name}"
            counter[0] += 1
            for doc in A.docs:
                claims.append({"claim_id": cid if len(A.docs) == 1 else f"{cid}_{Path(doc).stem.lower()}",
                               "source_id": "S1b", "doc": doc, "template": tmpl, "artifact": artifact,
                               "expr": expr, "fmt": f, "note": f"Phase I table cell ({slug}, {name}); generated by ops/phase_i_tables.py"})
        parts.append(text)
    return "| " + " | ".join(parts) + " |"


lines = []
A_SYN = " (SYNTHETIC dry run — not a result)" if A.synthetic else ""

# ---- Table A: the primary family ------------------------------------------
lines += [f"**Table 8b.1 — The pre-specified primary family: two outcomes × two arms × two strata{A_SYN}.** "
          "First-week mean coefficient with its date-clustered SE, the joint Wald statistic on days 0–7, "
          "the randomization p at 2,000 draws, the Benjamini–Hochberg-adjusted p over the family of eight, "
          "and the asymptotic p beside it.", "",
          "| stratum | outcome | arm | episodes | first-week mean | SE | joint χ² | RI p | BH p | asymptotic p |",
          "|---|---|---|---|---|---|---|---|---|---|"]
for s, sl in STRATA.items():
    if s == "pooled":
        continue
    for o in H1_OUTCOMES:
        for est in ("OLS_share", "PPML_count_offset"):
            col = o if est == "OLS_share" else count_outcome(o)
            r = res[(res.stratum == s) & (res.spec == "primary") & (res.outcome == col) & (res.estimator == est)]
            assert len(r) == 1, (s, col, est)
            r = r.iloc[0]
            w = where(s, "primary", col, est)
            slug = f"conf_primary_{sl}_{col}_{ARM_LABEL[est]}"
            lines.append(emit_row([sl, OUT_LABEL[col], ARM_LABEL[est]], [
                (int(r.n_episodes), "{}", f"int({w}['n_episodes'].iloc[0])", "episodes"),
                (r.first_week_mean_coef, "{:.5f}", f"float({w}['first_week_mean_coef'].iloc[0])", "mean"),
                (r.get("first_week_mean_se", np.nan), "{:.5f}", f"float({w}['first_week_mean_se'].iloc[0])", "se"),
                (r.first_week_chi2, "{:.2f}", f"float({w}['first_week_chi2'].iloc[0])", "chi2"),
                (r.p_randomization, "{:.4f}", f"float({w}['p_randomization'].iloc[0])", "p_ri"),
                (r.p_bh_adjusted, "{:.4f}", f"float({w}['p_bh_adjusted'].iloc[0])", "p_bh"),
                (r.p_asymptotic, "{:.4f}", f"float({w}['p_asymptotic'].iloc[0])", "p_asym"),
            ], slug, RES))
lines.append("")

# ---- Table B: the reading --------------------------------------------------
lines += [f"**Table 8b.2 — The pre-registered reading, applied by code (addendum §23, §19 rule 2, §25){A_SYN}.**", "",
          "| stratum | null certified | stratum rejects | placebo rejects | pre-freeze MDE, sustained | × family correction | pre-freeze MDE, transient |",
          "|---|---|---|---|---|---|---|"]
for s in ("C1_clean", "C2_exposed"):
    g = rdg[rdg.stratum == s].set_index("item")["value"]
    def rv(item):
        return f"float(d[(d.stratum=='{s}')&(d.item=='{item}')]['value'].iloc[0])"
    sl = STRATA[s]
    lines.append(emit_row([sl], [
        (int(float(g["null_certified"])), "{}", f"int({rv('null_certified')})", "certified"),
        (int(float(g["stratum_rejects"])), "{}", f"int({rv('stratum_rejects')})", "rejects"),
        (int(float(g["placebo_rejects_any"])), "{}", f"int({rv('placebo_rejects_any')})", "placebo"),
        (float(g["mde_level_prefreeze"]) if "mde_level_prefreeze" in g else np.nan, "{:.5f}", rv("mde_level_prefreeze"), "mde_level"),
        (float(g["mde_level_family_corrected"]) if "mde_level_family_corrected" in g else np.nan, "{:.5f}", rv("mde_level_family_corrected"), "mde_level_fam"),
        (float(g["mde_dip_rebound_prefreeze"]) if "mde_dip_rebound_prefreeze" in g else np.nan, "{:.5f}", rv("mde_dip_rebound_prefreeze"), "mde_dip"),
    ], f"conf_reading_{sl}", RDG))
    lines.append(f"| {sl} reading | {g['reading_9_4_input']} | | | | | |")
concl = rdg[(rdg.stratum == "family") & (rdg.item == "conclusion_9_4")]["value"].iloc[0]
lines += ["", f"*Conclusion under note §9.4 as amended: {concl}*", ""]

# ---- Table C: placebos and denominator diagnostics -------------------------
lines += [f"**Table 8b.3 — Falsification outcomes and the denominator diagnostic, per stratum (unadjusted randomization p; addendum §23.3–23.4){A_SYN}.**", "",
          "| stratum | outcome | arm | episodes | first-week mean | RI p | asymptotic p |", "|---|---|---|---|---|---|---|"]
for s in ("C1_clean", "C2_exposed"):
    sl = STRATA[s]
    sub = res[(res.stratum == s) & (res.family.isin(["placebo", "diagnostic"]))]
    for r in sub.itertuples():
        w = where(s, r.spec, r.outcome, r.estimator)
        slug = f"conf_{r.family}_{sl}_{r.outcome}_{ARM_LABEL[r.estimator].replace(', ', '_').replace(' ', '_')}"
        lines.append(emit_row([sl, OUT_LABEL[r.outcome], ARM_LABEL[r.estimator]], [
            (int(r.n_episodes), "{}", f"int({w}['n_episodes'].iloc[0])", "episodes"),
            (r.first_week_mean_coef, "{:.5f}", f"float({w}['first_week_mean_coef'].iloc[0])", "mean"),
            (r.p_randomization, "{:.4f}", f"float({w}['p_randomization'].iloc[0])", "p_ri"),
            (r.p_asymptotic, "{:.4f}", f"float({w}['p_asymptotic'].iloc[0])", "p_asym"),
        ], slug, RES))
lines.append("")

# ---- Table D: sensitivities -------------------------------------------------
lines += [f"**Table 8b.4 — Pre-registered sensitivities, reported beside the primary and never substituted for it (note §9.5){A_SYN}.** "
          "IDENTICAL means the arm's episode starts in that stratum equal the primary's, so no second p-value is printed (addendum §23.6).", "",
          "| stratum | sensitivity | outcome | arm | episodes | first-week mean | RI p |", "|---|---|---|---|---|---|---|"]
for s in ("C1_clean", "C2_exposed", "pooled"):
    sl = STRATA[s]
    sub = res[(res.stratum == s) & (res.family == "sensitivity")]
    for r in sub.itertuples():
        if not str(r.status).startswith("OK"):
            lines.append(f"| {sl} | {SPEC_LABEL.get(r.spec, r.spec)} | {OUT_LABEL.get(r.outcome, r.outcome)} | {ARM_LABEL.get(r.estimator, r.estimator)} | {str(r.status).split(':')[0]} | | |")
            continue
        w = where(s, r.spec, r.outcome, r.estimator)
        slug = f"conf_sens_{sl}_{r.spec}_{r.outcome}_{ARM_LABEL[r.estimator]}"
        lines.append(emit_row([sl, SPEC_LABEL.get(r.spec, r.spec), OUT_LABEL[r.outcome], ARM_LABEL[r.estimator]], [
            (int(r.n_episodes), "{}", f"int({w}['n_episodes'].iloc[0])", "episodes"),
            (r.first_week_mean_coef, "{:.5f}", f"float({w}['first_week_mean_coef'].iloc[0])", "mean"),
            (r.p_randomization, "{:.4f}", f"float({w}['p_randomization'].iloc[0])", "p_ri"),
        ], slug, RES))
lines.append("")

# ---- Table E: pooled (descriptive) and the B-HEARD interaction (secondary) --
lines += [f"**Table 8b.5 — The pooled stratum (descriptive, outside the family) and the B-HEARD interaction arm (secondary, asymptotic p only; note §10){A_SYN}.**", "",
          "| stratum | item | outcome | arm | episodes | coefficient | RI p | asymptotic p |", "|---|---|---|---|---|---|---|---|"]
for r in res[(res.stratum == "pooled") & (res.family == "descriptive")].itertuples():
    w = where("pooled", r.spec, r.outcome, r.estimator)
    lines.append(emit_row(["pooled", "primary design", OUT_LABEL[r.outcome], ARM_LABEL[r.estimator]], [
        (int(r.n_episodes), "{}", f"int({w}['n_episodes'].iloc[0])", "episodes"),
        (r.first_week_mean_coef, "{:.5f}", f"float({w}['first_week_mean_coef'].iloc[0])", "mean"),
        (r.p_randomization, "{:.4f}", f"float({w}['p_randomization'].iloc[0])", "p_ri"),
        (r.p_asymptotic, "{:.4f}", f"float({w}['p_asymptotic'].iloc[0])", "p_asym"),
    ], f"conf_pooled_{r.outcome}_{ARM_LABEL[r.estimator]}", RES))
for r in res[res.family == "secondary"].itertuples():
    w = where(r.stratum, r.spec, r.outcome, r.estimator)
    sl = STRATA[r.stratum]
    lines.append(emit_row([sl, "B-HEARD interaction", OUT_LABEL[r.outcome], ARM_LABEL[r.estimator]], [
        (int(r.n_episodes), "{}", f"int({w}['n_episodes'].iloc[0])", "episodes"),
        (r.first_week_mean_coef, "{:.5f}", f"float({w}['first_week_mean_coef'].iloc[0])", "coef"),
        (np.nan, "{:.4f}", "", "p_ri"),
        (r.p_asymptotic, "{:.4f}", f"float({w}['p_asymptotic'].iloc[0])", "p_asym"),
    ], f"conf_interaction_{sl}_{r.outcome}_{ARM_LABEL[r.estimator]}", RES))
lines.append("")

out = ROOT / A.out
out.mkdir(parents=True, exist_ok=True)
(out / "tables.md").write_text("\n".join(lines))
with open(out / "claims.csv", "w", newline="") as fh:
    w = csv.DictWriter(fh, fieldnames=["claim_id", "source_id", "doc", "template", "artifact", "expr", "fmt", "note"],
                       lineterminator="\r\n")
    w.writeheader(); w.writerows(claims)
# every template must be unique within its document, or the verifier anchors on the wrong row
tm = pd.Series([c["template"] for c in claims if c["doc"] == A.docs[0]])
dup = tm[tm.duplicated()]
print(f"wrote {out/'tables.md'} ({len(lines)} lines) and {out/'claims.csv'} ({len(claims)} rows; "
      f"next free id C{counter[0]}); duplicate templates: {len(dup)}")
if len(dup):
    print(dup.to_string())
