#!/usr/bin/env python3
"""Replace the generated claims in docs/CLAIMS_REGISTER.csv with the generators' current output.

    python3 ops/refresh_generated_claims.py

Rows whose note names one of the generators (ops/phase_i_tables.py, ops/paper_confirmatory_tables.py,
ops/supplement_tables.py) are dropped and the current claims.csv of each generator is appended, so the
register always equals the generators' output for every generated table cell. Hand-written rows are untouched.
The register is CRLF and written through the csv module.
"""
from __future__ import annotations

import csv
import io
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REG = ROOT / "docs" / "CLAIMS_REGISTER.csv"
GENERATORS = {
    "ops/phase_i_tables.py": [ROOT / "ops/state/phase_i_tables_supp/claims.csv"],
    "ops/paper_confirmatory_tables.py": [ROOT / "ops/state/paper_tables/claims.csv"],
    "ops/supplement_tables.py": [ROOT / "ops/state/supplement_tables/claims.csv"],
}

rows = list(csv.DictReader(open(REG, newline="", encoding="utf-8")))
fields = list(rows[0].keys())
kept = [r for r in rows if not any(f"generated by {g}" in r["note"] for g in GENERATORS)]
new = []
for g, paths in GENERATORS.items():
    for p in paths:
        if p.exists():
            new += list(csv.DictReader(open(p, newline="", encoding="utf-8")))
ids = [r["claim_id"] for r in kept + new]
dup = {i for i in ids if ids.count(i) > 1}
assert not dup, f"duplicate claim ids: {sorted(dup)[:5]}"
buf = io.StringIO()
w = csv.DictWriter(buf, fieldnames=fields, lineterminator="\r\n")
w.writeheader(); w.writerows(kept); w.writerows(new)
REG.write_text(buf.getvalue(), encoding="utf-8", newline="")
print(f"register: {len(rows)} -> {len(kept)} hand-written + {len(new)} generated = {len(kept) + len(new)}")
