#!/usr/bin/env python3
"""Supplementary tables that are not the sealed run's (those come from ops/phase_i_tables.py):

    python3 ops/supplement_tables.py --out ops/state/supplement_tables [--doc docs/SUPPLEMENT.md] [--start 3000]

- the complete dispatch-code list with family and first/last date (RECORD 7.1), from
  data/reference/ems_call_code_span.csv and config.CALL_TYPE_GROUPS (no numeric claims: dates are labels);
- the precinct–district crosswalk's concentration (RECORD 12.3), from data/reference/precinct_cd_crosswalk.csv;
- the null-calibration certificates, from outputs/tables/null_calibration_*.csv;
- the pre-freeze power table, from data/reference/power_analysis_prefreeze.csv.

Every numeric cell registers a claim (template = the row up to the cell); the source id of a claim is copied
from an existing register row on the same artifact where one exists, else '-'. The register replaces the rows
whose note names this script whenever it is re-run.
"""
from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from config import CALL_TYPE_GROUPS  # noqa: E402

ap = argparse.ArgumentParser()
ap.add_argument("--out", required=True)
ap.add_argument("--doc", default="docs/SUPPLEMENT.md")
ap.add_argument("--start", type=int, default=3000)
A = ap.parse_args()
NOTE = "generated by ops/supplement_tables.py"
MINUS = "−"
reg = pd.read_csv(ROOT / "docs" / "CLAIMS_REGISTER.csv")


def source_id_for(artifact):
    hit = reg[reg.artifact == artifact]
    return str(hit.source_id.iloc[0]) if len(hit) else "-"


claims, counter = [], [A.start]


def fmt(v, f):
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "—"
    return f.format(v).replace("-", MINUS)


def row(prefix, cells, slug, artifact):
    parts = list(prefix)
    for text, nums in cells:
        if not nums:
            parts.append(text); continue
        rendered = [fmt(v, f) for v, f, _, _ in nums]
        cell = text.format(*rendered) if text else rendered[0]
        for k, (v, f, expr, name) in enumerate(nums):
            if rendered[k] == "—":
                continue
            marks = list(rendered); marks[k] = "{}"
            tmpl = "| " + " | ".join(parts) + " | " + (text.format(*marks) if text else "{}") + " |"
            claims.append({"claim_id": f"C{counter[0]}_{slug}_{name}", "source_id": source_id_for(artifact), "doc": A.doc,
                           "template": tmpl, "artifact": artifact, "expr": expr, "fmt": f, "note": f"Supplement table cell ({slug}, {name}); {NOTE}"})
            counter[0] += 1
        parts.append(cell)
    return "| " + " | ".join(parts) + " |"


lines = []
# ---- code list ----------------------------------------------------------------------------
span = pd.read_csv(ROOT / "data/reference/ems_call_code_span.csv")
code_to_family = {c: g for g, codes in CALL_TYPE_GROUPS.items() for c in codes}
FAMILY = {"edp": "EDP (primary)", "altmen": "altered mental status (narrow MH)", "suicide_jump": "suicide-related (narrow MH)",
          "od_poison_drug": "overdose / poison / drug", "cardiac": "cardiac (falsification)", "injury": "injury (marker)",
          "asthma": "asthma (falsification)"}
span["family"] = span.final_call_type.map(code_to_family).map(FAMILY).fillna("other (denominator only)")
span = span.sort_values(["family", "final_call_type"])
lines += [f"**Table S7 — Every dispatch call type in the extract ({len(span)} codes), its outcome family and its first and last "
          "date in the data (RECORD 7.1).** Families are `config.CALL_TYPE_GROUPS`; a code outside every family counts in the "
          "denominator only. Source: `data/reference/ems_call_code_span.csv` (`35_coverage_breaks.py`).", "",
          "| code | family | first date | last date |", "|---|---|---|---|"]
for r in span.itertuples():
    lines.append(f"| `{r.final_call_type}` | {r.family} | {r.first_date} | {r.last_date} |")
lines.append("")

# ---- crosswalk concentration --------------------------------------------------------------
XW = "data/reference/precinct_cd_crosswalk.csv"
xw = pd.read_csv(ROOT / XW)
g = xw.groupby("policeprecinct")["n"].agg(["sum", "max"])
modal = g["max"] / g["sum"]
lines += ["**Table S8 — The precinct–district crosswalk that carries B-HEARD exposure onto community districts (RECORD 12.3).** "
          "Built from the dispatch data's own precinct and community-district fields (a count of dispatches per precinct × "
          "district over 2015–2024; freeze incident F4); the concentration statistics say how cleanly a precinct maps to one "
          "district. Source: `data/reference/precinct_cd_crosswalk.csv` (`16_bheard_exposure.py`).", "",
          "| statistic | value |", "|---|---|"]
lines.append(row(["precincts in the crosswalk"], [(None, [(int(g.shape[0]), "{}", "int(d.policeprecinct.nunique())", "n_precincts")])], "s8", XW))
lines.append(row(["precinct × district pairs"], [(None, [(int(len(xw)), "{}", "int(len(d))", "n_pairs")])], "s8", XW))
lines.append(row(["median share of a precinct's dispatches in its modal district"],
                 [(None, [(float(modal.median()), "{:.3f}", "float((d.groupby('policeprecinct')['n'].max()/d.groupby('policeprecinct')['n'].sum()).median())", "modal_median")])], "s8", XW))
lines.append(row(["minimum share in the modal district"],
                 [(None, [(float(modal.min()), "{:.3f}", "float((d.groupby('policeprecinct')['n'].max()/d.groupby('policeprecinct')['n'].sum()).min())", "modal_min")])], "s8", XW))
lines.append(row(["precincts with at least 0.90 of dispatches in the modal district"],
                 [(None, [(int((modal >= 0.9).sum()), "{}", "int(((d.groupby('policeprecinct')['n'].max()/d.groupby('policeprecinct')['n'].sum())>=0.9).sum())", "modal_ge90")])], "s8", XW))
lines.append("")

# ---- calibration certificates -------------------------------------------------------------
lines += ["**Table S9 — The null-calibration certificates that precede every randomization p-value.** Synthetic panels with no "
          "effect, carrying the dependence measured on the discovery rows, on each stratum's own episode geometry and draw "
          "scheme; the empirical rejection rate at α = 0.05 must lie inside its binomial band and the p-values must be uniform "
          "on the exact lattice (Kolmogorov–Smirnov with a simulated null). Sources: `outputs/tables/null_calibration_*.csv` "
          "(`18_null_calibration.py`, regenerated by `ops/calib1000.sh`; hashes pinned in the sealed run's sidecar).", "",
          "| stratum | draw scheme | episodes | simulations | rejection rate at α = 0.05 | KS p (uniformity) | verdict |",
          "|---|---|---|---|---|---|---|"]
CERTS = [("discovery", "outputs/tables/null_calibration_n1000.csv"), ("C1", "outputs/tables/null_calibration_C1.csv"),
         ("C2", "outputs/tables/null_calibration_C2.csv"), ("pooled", "outputs/tables/null_calibration_pooled.csv")]
for name, path in CERTS:
    c = pd.read_csv(ROOT / path).set_index("metric")["value"]
    assert str(c.get("stratum", name)).lower().startswith(name.lower()[:3]) or name == "discovery", (name, c.get("stratum"))
    lines.append(row([name, str(c["draw_scheme"])], [
        (None, [(int(float(c["n_episodes"])), "{}", "int(float(d.set_index('metric')['value'].loc['n_episodes']))", "episodes")]),
        (None, [(int(float(c["n_sims_completed"])), "{:,}", "int(float(d.set_index('metric')['value'].loc['n_sims_completed']))", "sims")]),
        (None, [(float(c["empirical_rejection_rate"]), "{:.3f}", "float(d.set_index('metric')['value'].loc['empirical_rejection_rate'])", "rejection")]),
        (None, [(float(c["ks_p_uniform"]), "{:.4f}", "float(d.set_index('metric')['value'].loc['ks_p_uniform'])", "ks_p")]),
        (str(c["VERDICT"]), []),
    ], f"s9_{name}", path))
lines.append("")

# ---- power ---------------------------------------------------------------------------------
PW = "data/reference/power_analysis_prefreeze.csv"
pw = pd.read_csv(ROOT / PW).set_index("metric")["value"]


def metric(stratum, pattern):
    hits = [m for m in pw.index if re.match(rf"^{stratum}\.{pattern}$", m)]
    assert len(hits) == 1, (stratum, pattern, hits)
    return hits[0]


lines += ["**Table S10 — The pre-freeze power table (EDP share only): the minimum detectable effect at 80% power for a sustained "
          "first-week shift and for a dip-and-rebound, against the declared minimum effect of interest of −0.005.** Source: "
          "`data/reference/power_analysis_prefreeze.csv` (`19_power.py`, computed before the lift; `freeze_active=1`). The MDE is "
          "measured against the asymptotic joint-Wald test at nominal α; the plan's addendum 23.11–23.12 states the bound's "
          "limitations. The last column is the same sustained-shift MDE measured against the randomization test where the "
          "pre-freeze table could bracket it (`mde_ri`); C1's two-block geometry left it undefined before the lift.", "",
          "| stratum | MDE, sustained shift | MDE, dip-and-rebound | MDE ÷ minimum effect of interest | verdict | MDE, sustained shift, randomization test |",
          "|---|---|---|---|---|---|"]
for st in ("discovery", "C1", "C2"):
    m_level = metric(st, r"mde_worst_profile")     # the sustained-shift MDE the reader uses (34: mde_level_prefreeze)
    m_dip = metric(st, r"mde_best_profile")        # the dip-and-rebound MDE (34: mde_dip_rebound_prefreeze)
    m_ratio = metric(st, r"mde_over_reference\.minimum_of_interest")
    m_verdict = metric(st, r"POWER_VERDICT")
    m_ri = metric(st, r"mde_ri")
    ri_val = pw[m_ri]
    ri_cell = ("not defined", []) if (ri_val is None or ri_val == "" or (isinstance(ri_val, float) and np.isnan(ri_val))) else \
        (None, [(float(ri_val), "{:.5f}", f"float(d.set_index('metric')['value'].loc['{m_ri}'])", "mde_ri")])
    lines.append(row([st], [
        (None, [(float(pw[m_level]), "{:.5f}", f"float(d.set_index('metric')['value'].loc['{m_level}'])", "mde_level")]),
        (None, [(float(pw[m_dip]), "{:.5f}", f"float(d.set_index('metric')['value'].loc['{m_dip}'])", "mde_dip")]),
        (None, [(float(pw[m_ratio]), "{:.3f}", f"float(d.set_index('metric')['value'].loc['{m_ratio}'])", "ratio")]),
        (str(pw[m_verdict]), []),
        ri_cell,
    ], f"s10_{st}", PW))
lines.append("")

out = ROOT / A.out
out.mkdir(parents=True, exist_ok=True)
(out / "tables.md").write_text("\n".join(lines), encoding="utf-8")
with open(out / "claims.csv", "w", newline="", encoding="utf-8") as fh:
    w = csv.DictWriter(fh, fieldnames=["claim_id", "source_id", "doc", "template", "artifact", "expr", "fmt", "note"], lineterminator="\r\n")
    w.writeheader(); w.writerows(claims)
print(f"wrote {out/'tables.md'} ({len(lines)} lines) and {out/'claims.csv'} ({len(claims)} rows; next free id C{counter[0]})")
